<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Support\Str;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\ImmatriculationDirecte;

class ImmatriculationDirecteSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $steps = [
            '1- Création du Dossier',
            '2- Cotation du Dossier au Csdaf',
            '3- Délivrance de l\'Ordre de Versement',
            '4- Changements de Statut après la Publication d’Avis',
            '5- Génération du Certificat d\'Affichage',
            '6- Changements de Statut liés au Certificat d\'Affichage',
            '7- Enregistrement de la Descente sur le Terrain',
            '8- Établissement de l\'État de Cession et Paiement',
            '9- Instruction de la Descente sur le Terrain',
            '10- Changement de Statut après la Descente sur le Terrain',
            '11- Mise à Jour du Dossier Technique',
            '12- Mise en Forme du Dossier Administratif',
            '13- Changements de Statut après Transmission',
            '14- Établissement du Bordereau de Transmission',
            '15- Changements de Statut après le Bordereau',
            '16- Production du Certificat Final',
            '17- Finalisation et Clôture du Dossier',
            '18- Vérification Finale',
            '19- Remise des Documents Officiels',
            '20- Archivage du Dossier',
        ];


        $elements = [[
            'uuid' => 01,
            'reference' => 'REF-00000001',
            'localisation' => 'Localisation 1',
            'region_id' => 1, // rand(1, 10)
            'division_id' => 1, // rand(1, 10)
            'sub_division_id' => 1, // rand(1, 10)
            'zone' => 'Zone 1',
            'etat_terrain' => 'Etat 1',
            'duplicata' => null,
            'source_terrain' => 'Source 1',
            'superficie' => 100, //rand(100, 1000)
            'volume' => 'Volume 1',
            'folio' => 'Folio 1',
            'numero_cp' => 'CP-00001',  //Str::random(5),
            'titre_foncier_id' => 1, //rand(1, 10)
            'numero_bordereau_transmission' => 'BT-00001', //Str::random(5),
            'next_step' => $steps[array_rand($steps)],
            'statut' => 'En cours',
            'StatutStyle' => 'primary',
            'date_delivrance' => now()->subDays(rand(1, 365)),
            'comissions' => json_encode(['Commission 1', 'Commission 2']),
            'service_id' => 1, //rand(1, 5)
            'cotation_user_id' => 1, //rand(1, 5)
            'observation_cotation' => 'Observation cotation 1',
            'date_cotation' => now()->subDays(rand(1, 365)),
            'status_cotation' => 'done',
            'montant_ordre_versement' => 1000, //rand(1000, 5000)
            'numero_ordre_versement' => 'OV-00001', //Str::random(5),
            'numero_arrete_ordre_versement' => 'AO-00001', //Str::random(5),
            'date_ordre_versement' => now()->subDays(rand(1, 365)),
            'status_ordre_versement' => 'done',
            'status_avis_publique' => 'done',
            'date_avis_publique' => now()->subDays(rand(1, 365)),
            'date_avis_publique_signe' => now()->subDays(rand(1, 365)),
            'calendar_decision' => 'Calendrier 1',
            'calendar_decision_date' => now()->subDays(rand(1, 365)),
            'date_debut_certificat_d_affichage' => now()->subDays(rand(1, 365)),
            'date_fin_certificat_d_affichage' => now()->subDays(rand(1, 365)),
            'date_certificat_d_affichage_signer' => now()->subDays(rand(1, 365)),
            'date_convocation' => now()->subDays(rand(1, 365)),
            'status_convocation' => 'Statut convocation 1',
            'geometre_id' => 1, //rand(1, 5)
            'date_geometre_enregistrer' => now()->subDays(rand(1, 365)),
            'pv_enregistrer' => now()->subDays(rand(1, 365)),
            'dossier_technique_complet' => now()->subDays(rand(1, 365)),
            'dossier_jumelage' => now()->subDays(rand(1, 365)),
            'transmission_csdaf' => now()->subDays(rand(1, 365)),
            'dossier_administratif_complet' => now()->subDays(rand(1, 365)),
            'dossier_technique_enregistrer' => now()->subDays(rand(1, 365)),
            'etat_cession_id' => 1, //rand(1, 10)
            'etat_cession' => now()->subDays(rand(1, 365)),
            'etat_cession_payer' => now()->subDays(rand(1, 365)),
            'date_publication_dossier_vise' => now()->subDays(rand(1, 365)),
            'date_signature_bulletin' => now()->subDays(rand(1, 365)),
            'coordonnees' => json_encode(['lat' => rand(0, 90), 'lng' => rand(0, 180)]),
            'limit_nord' => 'Nord 1',
            'limit_sud' => 'Sud 1',
            'limit_est' => 'Est 1',
            'limit_ouest' => 'Ouest 1',
            'dossier_technique_created' => now()->subDays(rand(1, 365)),
            'descente_terrain' => now()->subDays(rand(1, 365)),
            'transmission_dos_tech_csdaf' => now()->subDays(rand(1, 365)),
            'transmission_delegue_departemental' => now()->subDays(rand(1, 365)),
            'transmission_delegue_regional' => now()->subDays(rand(1, 365)),
            'date_calendrier_descente' => now()->subDays(rand(1, 365)),
            'service' => 'Service 1',
            'date_dossier_signe_csr_cadastre' => now()->subDays(rand(1, 365)),
            'date_dossier_transmi_au_Mindcaf' => now()->subDays(rand(1, 365)),
            'date_dossier_complet_transmi_CSRegional_mindcaf' => now()->subDays(rand(1, 365)),
            'date_dossier_vise_en_attente_publication' => now()->subDays(rand(1, 365)),
            'service_dossier_complet_id' => 1, //rand(1, 5)
            'user_dossier_complet_id' => 1, //rand(1, 5)
            'observation_dossier_complet' => 'Observation dossier complet 1',
            'date_dossier_complet_vise_coter' => now()->subDays(rand(1, 365)),
            'numero_redevance_fonciere' => 'RF-00001', //Str::random(5),
            'ordre_redevance_fonciere' => now()->subDays(rand(1, 365)),
            'montant_ordre_redevance_fonciere' => 1000, //rand(1000, 5000)
            'cadre_id' => 1, //rand(1, 5)
            'observation_cotation_cadre' => 'Observation cotation cadre 1',
            'date_cotation_cadre' => now()->subDays(rand(1, 365)),
            'coter_csrcadastre' => now()->subDays(rand(1, 365)),
            'dos_tech_transmis_drm' => now()->subDays(rand(1, 365)),
            'dos_compl_csrdaf' => now()->subDays(rand(1, 365)),
            'cotation_compl_csrdaf' => now()->subDays(rand(1, 365)),
            'numero_serie' => 'NS-00001', //Str::random(5),
            'is_finalisation' => 'non',
            'is_complete' => 0, //rand(0, 1)
        ], [
            'uuid' => 02,
            'reference' => 'REF-00000002',
            'localisation' => 'Localisation 2',
            'region_id' => 2, // rand(1, 10)
            'division_id' => 2, // rand(1, 10)
            'sub_division_id' => 2, // rand(1, 10)
            'zone' => 'Zone 2',
            'etat_terrain' => 'Etat 2',
            'duplicata' => null,
            'source_terrain' => 'Source 2',
            'superficie' => 101, //rand(100, 1000)
            'volume' => 'Volume 2',
            'folio' => 'Folio 2',
            'numero_cp' => 'CP-00002',  //Str::random(5),
            'titre_foncier_id' => 2, //rand(1, 10)
            'numero_bordereau_transmission' => 'BT-00002', //Str::random(5),
            'next_step' => $steps[array_rand($steps)],
            'statut' => 'En cours',
            'StatutStyle' => 'primary',
            'date_delivrance' => now()->subDays(rand(1, 365)),
            'comissions' => json_encode(['Commission 2', 'Commission 3']),
            'service_id' => 2, //rand(1, 5)
            'cotation_user_id' => 2, //rand(1, 5)
            'observation_cotation' => 'Observation cotation 2',
            'date_cotation' => now()->subDays(rand(1, 365)),
            'status_cotation' => 'done',
            'montant_ordre_versement' => 1001, //rand(1000, 5000)
            'numero_ordre_versement' => 'OV-00002', //Str::random(5),
            'numero_arrete_ordre_versement' => 'AO-00002', //Str::random(5),
            'date_ordre_versement' => now()->subDays(rand(1, 365)),
            'status_ordre_versement' => 'done',
            'status_avis_publique' => 'done',
            'date_avis_publique' => now()->subDays(rand(1, 365)),
            'date_avis_publique_signe' => now()->subDays(rand(1, 365)),
            'calendar_decision' => 'Calendrier 2',
            'calendar_decision_date' => now()->subDays(rand(1, 365)),
            'date_debut_certificat_d_affichage' => now()->subDays(rand(1, 365)),
            'date_fin_certificat_d_affichage' => now()->subDays(rand(1, 365)),
            'date_certificat_d_affichage_signer' => now()->subDays(rand(1, 365)),
            'date_convocation' => now()->subDays(rand(1, 365)),
            'status_convocation' => 'Statut convocation 2',
            'geometre_id' => 2, //rand(1, 5)
            'date_geometre_enregistrer' => now()->subDays(rand(1, 365)),
            'pv_enregistrer' => now()->subDays(rand(1, 365)),
            'dossier_technique_complet' => now()->subDays(rand(1, 365)),
            'dossier_jumelage' => now()->subDays(rand(1, 365)),
            'transmission_csdaf' => now()->subDays(rand(1, 365)),
            'dossier_administratif_complet' => now()->subDays(rand(1, 365)),
            'dossier_technique_enregistrer' => now()->subDays(rand(1, 365)),
            'etat_cession_id' => 2, //rand(1, 10)
            'etat_cession' => now()->subDays(rand(1, 365)),
            'etat_cession_payer' => now()->subDays(rand(1, 365)),
            'date_publication_dossier_vise' => now()->subDays(rand(1, 365)),
            'date_signature_bulletin' => now()->subDays(rand(1, 365)),
            'coordonnees' => json_encode(['lat' => rand(0, 90), 'lng' => rand(0, 180)]),
            'limit_nord' => 'Nord 2',
            'limit_sud' => 'Sud 2',
            'limit_est' => 'Est 2',
            'limit_ouest' => 'Ouest 2',
            'dossier_technique_created' => now()->subDays(rand(1, 365)),
            'descente_terrain' => now()->subDays(rand(1, 365)),
            'transmission_dos_tech_csdaf' => now()->subDays(rand(1, 365)),
            'transmission_delegue_departemental' => now()->subDays(rand(1, 365)),
            'transmission_delegue_regional' => now()->subDays(rand(1, 365)),
            'date_calendrier_descente' => now()->subDays(rand(1, 365)),
            'service' => 'Service 2',
            'date_dossier_signe_csr_cadastre' => now()->subDays(rand(1, 365)),
            'date_dossier_transmi_au_Mindcaf' => now()->subDays(rand(1, 365)),
            'date_dossier_complet_transmi_CSRegional_mindcaf' => now()->subDays(rand(1, 365)),
            'date_dossier_vise_en_attente_publication' => now()->subDays(rand(1, 365)),
            'service_dossier_complet_id' => 2, //rand(1, 5)
            'user_dossier_complet_id' => 2, //rand(1, 5)
            'observation_dossier_complet' => 'Observation dossier complet 2',
            'date_dossier_complet_vise_coter' => now()->subDays(rand(1, 365)),
            'numero_redevance_fonciere' => 'RF-00002', //Str::random(5),
            'ordre_redevance_fonciere' => now()->subDays(rand(1, 365)),
            'montant_ordre_redevance_fonciere' => 1001, //rand(1000, 5000)
            'cadre_id' => 2, //rand(1, 5)
            'observation_cotation_cadre' => 'Observation cotation cadre 2',
            'date_cotation_cadre' => now()->subDays(rand(1, 365)),
            'coter_csrcadastre' => now()->subDays(rand(1, 365)),
            'dos_tech_transmis_drm' => now()->subDays(rand(1, 365)),
            'dos_compl_csrdaf' => now()->subDays(rand(1, 365)),
            'cotation_compl_csrdaf' => now()->subDays(rand(1, 365)),
            'numero_serie' => 'NS-00002', //Str::random(5),
            'is_finalisation' => 'non',
            'is_complete' => 1, //rand(0, 1)
        ], [
            'uuid' => 03,
            'reference' => 'REF-00000003',
            'localisation' => 'Localisation 3',
            'region_id' => 3, // rand(1, 10)
            'division_id' => 3, // rand(1, 10)
            'sub_division_id' => 3, // rand(1, 10)
            'zone' => 'Zone 3',
            'etat_terrain' => 'Etat 3',
            'duplicata' => null,
            'source_terrain' => 'Source 3',
            'superficie' => 102, //rand(100, 1000)
            'volume' => 'Volume 3',
            'folio' => 'Folio 3',
            'numero_cp' => 'CP-00003',  //Str::random(5),
            'titre_foncier_id' => 3, //rand(1, 10)
            'numero_bordereau_transmission' => 'BT-00003', //Str::random(5),
            'next_step' => $steps[array_rand($steps)],
            'statut' => 'En cours',
            'StatutStyle' => 'primary',
            'date_delivrance' => now()->subDays(rand(1, 365)),
            'comissions' => json_encode(['Commission 3', 'Commission 4']),
            'service_id' => 3, //rand(1, 5)
            'cotation_user_id' => 3, //rand(1, 5)
            'observation_cotation' => 'Observation cotation 3',
            'date_cotation' => now()->subDays(rand(1, 365)),
            'status_cotation' => 'done',
            'montant_ordre_versement' => 1002, //rand(1000, 5000)
            'numero_ordre_versement' => 'OV-00003', //Str::random(5),
            'numero_arrete_ordre_versement' => 'AO-00003', //Str::random(5),
            'date_ordre_versement' => now()->subDays(rand(1, 365)),
            'status_ordre_versement' => 'done',
            'status_avis_publique' => 'done',
            'date_avis_publique' => now()->subDays(rand(1, 365)),
            'date_avis_publique_signe' => now()->subDays(rand(1, 365)),
            'calendar_decision' => 'Calendrier 3',
            'calendar_decision_date' => now()->subDays(rand(1, 365)),
            'date_debut_certificat_d_affichage' => now()->subDays(rand(1, 365)),
            'date_fin_certificat_d_affichage' => now()->subDays(rand(1, 365)),
            'date_certificat_d_affichage_signer' => now()->subDays(rand(1, 365)),
            'date_convocation' => now()->subDays(rand(1, 365)),
            'status_convocation' => 'Statut convocation 3',
            'geometre_id' => 3, //rand(1, 5)
            'date_geometre_enregistrer' => now()->subDays(rand(1, 365)),
            'pv_enregistrer' => now()->subDays(rand(1, 365)),
            'dossier_technique_complet' => now()->subDays(rand(1, 365)),
            'dossier_jumelage' => now()->subDays(rand(1, 365)),
            'transmission_csdaf' => now()->subDays(rand(1, 365)),
            'dossier_administratif_complet' => now()->subDays(rand(1, 365)),
            'dossier_technique_enregistrer' => now()->subDays(rand(1, 365)),
            'etat_cession_id' => 3, //rand(1, 10)
            'etat_cession' => now()->subDays(rand(1, 365)),
            'etat_cession_payer' => now()->subDays(rand(1, 365)),
            'date_publication_dossier_vise' => now()->subDays(rand(1, 365)),
            'date_signature_bulletin' => now()->subDays(rand(1, 365)),
            'coordonnees' => json_encode(['lat' => rand(0, 90), 'lng' => rand(0, 180)]),
            'limit_nord' => 'Nord 3',
            'limit_sud' => 'Sud 3',
            'limit_est' => 'Est 3',
            'limit_ouest' => 'Ouest 3',
            'dossier_technique_created' => now()->subDays(rand(1, 365)),
            'descente_terrain' => now()->subDays(rand(1, 365)),
            'transmission_dos_tech_csdaf' => now()->subDays(rand(1, 365)),
            'transmission_delegue_departemental' => now()->subDays(rand(1, 365)),
            'transmission_delegue_regional' => now()->subDays(rand(1, 365)),
            'date_calendrier_descente' => now()->subDays(rand(1, 365)),
            'service' => 'Service 3',
            'date_dossier_signe_csr_cadastre' => now()->subDays(rand(1, 365)),
            'date_dossier_transmi_au_Mindcaf' => now()->subDays(rand(1, 365)),
            'date_dossier_complet_transmi_CSRegional_mindcaf' => now()->subDays(rand(1, 365)),
            'date_dossier_vise_en_attente_publication' => now()->subDays(rand(1, 365)),
            'service_dossier_complet_id' => 3, //rand(1, 5)
            'user_dossier_complet_id' => 3, //rand(1, 5)
            'observation_dossier_complet' => 'Observation dossier complet 3',
            'date_dossier_complet_vise_coter' => now()->subDays(rand(1, 365)),
            'numero_redevance_fonciere' => 'RF-00003', //Str::random(5),
            'ordre_redevance_fonciere' => now()->subDays(rand(1, 365)),
            'montant_ordre_redevance_fonciere' => 1002, //rand(1000, 5000)
            'cadre_id' => 3, //rand(1, 5)
            'observation_cotation_cadre' => 'Observation cotation cadre 3',
            'date_cotation_cadre' => now()->subDays(rand(1, 365)),
            'coter_csrcadastre' => now()->subDays(rand(1, 365)),
            'dos_tech_transmis_drm' => now()->subDays(rand(1, 365)),
            'dos_compl_csrdaf' => now()->subDays(rand(1, 365)),
            'cotation_compl_csrdaf' => now()->subDays(rand(1, 365)),
            'numero_serie' => 'NS-00003', //Str::random(5),
            'is_finalisation' => 'non',
            'is_complete' => 1, //rand(0, 1)
        ], [
            'uuid' => 04,
            'reference' => 'REF-00000004',
            'localisation' => 'Localisation 4',
            'region_id' => 4, // rand(1, 10)
            'division_id' => 4, // rand(1, 10)
            'sub_division_id' => 4, // rand(1, 10)
            'zone' => 'Zone 4',
            'etat_terrain' => 'Etat 4',
            'duplicata' => null,
            'source_terrain' => 'Source 4',
            'superficie' => 103, //rand(100, 1000)
            'volume' => 'Volume 4',
            'folio' => 'Folio 4',
            'numero_cp' => 'CP-00004',  //Str::random(5),
            'titre_foncier_id' => 4, //rand(1, 10)
            'numero_bordereau_transmission' => 'BT-00004', //Str::random(5),
            'next_step' => $steps[array_rand($steps)],
            'statut' => 'En cours',
            'StatutStyle' => 'primary',
            'date_delivrance' => now()->subDays(rand(1, 365)),
            'comissions' => json_encode(['Commission 4', 'Commission 5']),
            'service_id' => 4, //rand(1, 5)
            'cotation_user_id' => 4, //rand(1, 5)
            'observation_cotation' => 'Observation cotation 4',
            'date_cotation' => now()->subDays(rand(1, 365)),
            'status_cotation' => 'done',
            'montant_ordre_versement' => 1003, //rand(1000, 5000)
            'numero_ordre_versement' => 'OV-00004', //Str::random(5),
            'numero_arrete_ordre_versement' => 'AO-00004', //Str::random(5),
            'date_ordre_versement' => now()->subDays(rand(1, 365)),
            'status_ordre_versement' => 'done',
            'status_avis_publique' => 'done',
            'date_avis_publique' => now()->subDays(rand(1, 365)),
            'date_avis_publique_signe' => now()->subDays(rand(1, 365)),
            'calendar_decision' => 'Calendrier 4',
            'calendar_decision_date' => now()->subDays(rand(1, 365)),
            'date_debut_certificat_d_affichage' => now()->subDays(rand(1, 365)),
            'date_fin_certificat_d_affichage' => now()->subDays(rand(1, 365)),
            'date_certificat_d_affichage_signer' => now()->subDays(rand(1, 365)),
            'date_convocation' => now()->subDays(rand(1, 365)),
            'status_convocation' => 'Statut convocation 4',
            'geometre_id' => 4, //rand(1, 5)
            'date_geometre_enregistrer' => now()->subDays(rand(1, 365)),
            'pv_enregistrer' => now()->subDays(rand(1, 365)),
            'dossier_technique_complet' => now()->subDays(rand(1, 365)),
            'dossier_jumelage' => now()->subDays(rand(1, 365)),
            'transmission_csdaf' => now()->subDays(rand(1, 365)),
            'dossier_administratif_complet' => now()->subDays(rand(1, 365)),
            'dossier_technique_enregistrer' => now()->subDays(rand(1, 365)),
            'etat_cession_id' => 4, //rand(1, 10)
            'etat_cession' => now()->subDays(rand(1, 365)),
            'etat_cession_payer' => now()->subDays(rand(1, 365)),
            'date_publication_dossier_vise' => now()->subDays(rand(1, 365)),
            'date_signature_bulletin' => now()->subDays(rand(1, 365)),
            'coordonnees' => json_encode(['lat' => rand(0, 90), 'lng' => rand(0, 180)]),
            'limit_nord' => 'Nord 4',
            'limit_sud' => 'Sud 4',
            'limit_est' => 'Est 4',
            'limit_ouest' => 'Ouest 4',
            'dossier_technique_created' => now()->subDays(rand(1, 365)),
            'descente_terrain' => now()->subDays(rand(1, 365)),
            'transmission_dos_tech_csdaf' => now()->subDays(rand(1, 365)),
            'transmission_delegue_departemental' => now()->subDays(rand(1, 365)),
            'transmission_delegue_regional' => now()->subDays(rand(1, 365)),
            'date_calendrier_descente' => now()->subDays(rand(1, 365)),
            'service' => 'Service 4',
            'date_dossier_signe_csr_cadastre' => now()->subDays(rand(1, 365)),
            'date_dossier_transmi_au_Mindcaf' => now()->subDays(rand(1, 365)),
            'date_dossier_complet_transmi_CSRegional_mindcaf' => now()->subDays(rand(1, 365)),
            'date_dossier_vise_en_attente_publication' => now()->subDays(rand(1, 365)),
            'service_dossier_complet_id' => 4, //rand(1, 5)
            'user_dossier_complet_id' => 4, //rand(1, 5)
            'observation_dossier_complet' => 'Observation dossier complet 4',
            'date_dossier_complet_vise_coter' => now()->subDays(rand(1, 365)),
            'numero_redevance_fonciere' => 'RF-00004', //Str::random(5),
            'ordre_redevance_fonciere' => now()->subDays(rand(1, 365)),
            'montant_ordre_redevance_fonciere' => 1003, //rand(1000, 5000)
            'cadre_id' => 4, //rand(1, 5)
            'observation_cotation_cadre' => 'Observation cotation cadre 4',
            'date_cotation_cadre' => now()->subDays(rand(1, 365)),
            'coter_csrcadastre' => now()->subDays(rand(1, 365)),
            'dos_tech_transmis_drm' => now()->subDays(rand(1, 365)),
            'dos_compl_csrdaf' => now()->subDays(rand(1, 365)),
            'cotation_compl_csrdaf' => now()->subDays(rand(1, 365)),
            'numero_serie' => 'NS-00004', //Str::random(5),
            'is_finalisation' => 'non',
            'is_complete' => 0, //rand(0, 1)
        ], [
            'uuid' => 05,
            'reference' => 'REF-00000005',
            'localisation' => 'Localisation 5',
            'region_id' => 5, // rand(1, 10)
            'division_id' => 5, // rand(1, 10)
            'sub_division_id' => 5, // rand(1, 10)
            'zone' => 'Zone 5',
            'etat_terrain' => 'Etat 5',
            'duplicata' => null,
            'source_terrain' => 'Source 5',
            'superficie' => 104, //rand(100, 1000)
            'volume' => 'Volume 5',
            'folio' => 'Folio 5',
            'numero_cp' => 'CP-00005',  //Str::random(5),
            'titre_foncier_id' => 5, //rand(1, 10)
            'numero_bordereau_transmission' => 'BT-00005', //Str::random(5),
            'next_step' => $steps[array_rand($steps)],
            'statut' => 'En cours',
            'StatutStyle' => 'primary',
            'date_delivrance' => now()->subDays(rand(1, 365)),
            'comissions' => json_encode(['Commission 5', 'Commission 6']),
            'service_id' => 5, //rand(1, 5)
            'cotation_user_id' => 5, //rand(1, 5)
            'observation_cotation' => 'Observation cotation 5',
            'date_cotation' => now()->subDays(rand(1, 365)),
            'status_cotation' => 'done',
            'montant_ordre_versement' => 1004, //rand(1000, 5000)
            'numero_ordre_versement' => 'OV-00005', //Str::random(5),
            'numero_arrete_ordre_versement' => 'AO-00005', //Str::random(5),
            'date_ordre_versement' => now()->subDays(rand(1, 365)),
            'status_ordre_versement' => 'done',
            'status_avis_publique' => 'done',
            'date_avis_publique' => now()->subDays(rand(1, 365)),
            'date_avis_publique_signe' => now()->subDays(rand(1, 365)),
            'calendar_decision' => 'Calendrier 5',
            'calendar_decision_date' => now()->subDays(rand(1, 365)),
            'date_debut_certificat_d_affichage' => now()->subDays(rand(1, 365)),
            'date_fin_certificat_d_affichage' => now()->subDays(rand(1, 365)),
            'date_certificat_d_affichage_signer' => now()->subDays(rand(1, 365)),
            'date_convocation' => now()->subDays(rand(1, 365)),
            'status_convocation' => 'Statut convocation 5',
            'geometre_id' => 5, //rand(1, 5)
            'date_geometre_enregistrer' => now()->subDays(rand(1, 365)),
            'pv_enregistrer' => now()->subDays(rand(1, 365)),
            'dossier_technique_complet' => now()->subDays(rand(1, 365)),
            'dossier_jumelage' => now()->subDays(rand(1, 365)),
            'transmission_csdaf' => now()->subDays(rand(1, 365)),
            'dossier_administratif_complet' => now()->subDays(rand(1, 365)),
            'dossier_technique_enregistrer' => now()->subDays(rand(1, 365)),
            'etat_cession_id' => 5, //rand(1, 10)
            'etat_cession' => now()->subDays(rand(1, 365)),
            'etat_cession_payer' => now()->subDays(rand(1, 365)),
            'date_publication_dossier_vise' => now()->subDays(rand(1, 365)),
            'date_signature_bulletin' => now()->subDays(rand(1, 365)),
            'coordonnees' => json_encode(['lat' => rand(0, 90), 'lng' => rand(0, 180)]),
            'limit_nord' => 'Nord 5',
            'limit_sud' => 'Sud 5',
            'limit_est' => 'Est 5',
            'limit_ouest' => 'Ouest 5',
            'dossier_technique_created' => now()->subDays(rand(1, 365)),
            'descente_terrain' => now()->subDays(rand(1, 365)),
            'transmission_dos_tech_csdaf' => now()->subDays(rand(1, 365)),
            'transmission_delegue_departemental' => now()->subDays(rand(1, 365)),
            'transmission_delegue_regional' => now()->subDays(rand(1, 365)),
            'date_calendrier_descente' => now()->subDays(rand(1, 365)),
            'service' => 'Service 5',
            'date_dossier_signe_csr_cadastre' => now()->subDays(rand(1, 365)),
            'date_dossier_transmi_au_Mindcaf' => now()->subDays(rand(1, 365)),
            'date_dossier_complet_transmi_CSRegional_mindcaf' => now()->subDays(rand(1, 365)),
            'date_dossier_vise_en_attente_publication' => now()->subDays(rand(1, 365)),
            'service_dossier_complet_id' => 5, //rand(1, 5)
            'user_dossier_complet_id' => 5, //rand(1, 5)
            'observation_dossier_complet' => 'Observation dossier complet 5',
            'date_dossier_complet_vise_coter' => now()->subDays(rand(1, 365)),
            'numero_redevance_fonciere' => 'RF-00005', //Str::random(5),
            'ordre_redevance_fonciere' => now()->subDays(rand(1, 365)),
            'montant_ordre_redevance_fonciere' => 1004, //rand(1000, 5000)
            'cadre_id' => 5, //rand(1, 5)
            'observation_cotation_cadre' => 'Observation cotation cadre 5',
            'date_cotation_cadre' => now()->subDays(rand(1, 365)),
            'coter_csrcadastre' => now()->subDays(rand(1, 365)),
            'dos_tech_transmis_drm' => now()->subDays(rand(1, 365)),
            'dos_compl_csrdaf' => now()->subDays(rand(1, 365)),
            'cotation_compl_csrdaf' => now()->subDays(rand(1, 365)),
            'numero_serie' => 'NS-00005', //Str::random(5),
            'is_finalisation' => 'non',
            'is_complete' => 0, //rand(0, 1)
        ], [
            'uuid' => 06,
            'reference' => 'REF-00000006',
            'localisation' => 'Localisation 6',
            'region_id' => 6, // rand(1, 10)
            'division_id' => 6, // rand(1, 10)
            'sub_division_id' => 6, // rand(1, 10)
            'zone' => 'Zone 6',
            'etat_terrain' => 'Etat 6',
            'duplicata' => null,
            'source_terrain' => 'Source 6',
            'superficie' => 105, //rand(100, 1000)
            'volume' => 'Volume 6',
            'folio' => 'Folio 6',
            'numero_cp' => 'CP-00006',  //Str::random(5),
            'titre_foncier_id' => 6, //rand(1, 10)
            'numero_bordereau_transmission' => 'BT-00006', //Str::random(5),
            'next_step' => $steps[array_rand($steps)],
            'statut' => 'En cours',
            'StatutStyle' => 'primary',
            'date_delivrance' => now()->subDays(rand(1, 365)),
            'comissions' => json_encode(['Commission 6', 'Commission 7']),
            'service_id' => 3, //rand(1, 5)
            'cotation_user_id' => 3, //rand(1, 5)
            'observation_cotation' => 'Observation cotation 6',
            'date_cotation' => now()->subDays(rand(1, 365)),
            'status_cotation' => 'done',
            'montant_ordre_versement' => 1005, //rand(1000, 5000)
            'numero_ordre_versement' => 'OV-00006', //Str::random(5),
            'numero_arrete_ordre_versement' => 'AO-00006', //Str::random(5),
            'date_ordre_versement' => now()->subDays(rand(1, 365)),
            'status_ordre_versement' => 'done',
            'status_avis_publique' => 'done',
            'date_avis_publique' => now()->subDays(rand(1, 365)),
            'date_avis_publique_signe' => now()->subDays(rand(1, 365)),
            'calendar_decision' => 'Calendrier 6',
            'calendar_decision_date' => now()->subDays(rand(1, 365)),
            'date_debut_certificat_d_affichage' => now()->subDays(rand(1, 365)),
            'date_fin_certificat_d_affichage' => now()->subDays(rand(1, 365)),
            'date_certificat_d_affichage_signer' => now()->subDays(rand(1, 365)),
            'date_convocation' => now()->subDays(rand(1, 365)),
            'status_convocation' => 'Statut convocation 6',
            'geometre_id' => 1, //rand(1, 5)
            'date_geometre_enregistrer' => now()->subDays(rand(1, 365)),
            'pv_enregistrer' => now()->subDays(rand(1, 365)),
            'dossier_technique_complet' => now()->subDays(rand(1, 365)),
            'dossier_jumelage' => now()->subDays(rand(1, 365)),
            'transmission_csdaf' => now()->subDays(rand(1, 365)),
            'dossier_administratif_complet' => now()->subDays(rand(1, 365)),
            'dossier_technique_enregistrer' => now()->subDays(rand(1, 365)),
            'etat_cession_id' => 6, //rand(1, 10)
            'etat_cession' => now()->subDays(rand(1, 365)),
            'etat_cession_payer' => now()->subDays(rand(1, 365)),
            'date_publication_dossier_vise' => now()->subDays(rand(1, 365)),
            'date_signature_bulletin' => now()->subDays(rand(1, 365)),
            'coordonnees' => json_encode(['lat' => rand(0, 90), 'lng' => rand(0, 180)]),
            'limit_nord' => 'Nord 6',
            'limit_sud' => 'Sud 6',
            'limit_est' => 'Est 6',
            'limit_ouest' => 'Ouest 6',
            'dossier_technique_created' => now()->subDays(rand(1, 365)),
            'descente_terrain' => now()->subDays(rand(1, 365)),
            'transmission_dos_tech_csdaf' => now()->subDays(rand(1, 365)),
            'transmission_delegue_departemental' => now()->subDays(rand(1, 365)),
            'transmission_delegue_regional' => now()->subDays(rand(1, 365)),
            'date_calendrier_descente' => now()->subDays(rand(1, 365)),
            'service' => 'Service 6',
            'date_dossier_signe_csr_cadastre' => now()->subDays(rand(1, 365)),
            'date_dossier_transmi_au_Mindcaf' => now()->subDays(rand(1, 365)),
            'date_dossier_complet_transmi_CSRegional_mindcaf' => now()->subDays(rand(1, 365)),
            'date_dossier_vise_en_attente_publication' => now()->subDays(rand(1, 365)),
            'service_dossier_complet_id' => 3, //rand(1, 5)
            'user_dossier_complet_id' => 3, //rand(1, 5)
            'observation_dossier_complet' => 'Observation dossier complet 6',
            'date_dossier_complet_vise_coter' => now()->subDays(rand(1, 365)),
            'numero_redevance_fonciere' => 'RF-00006', //Str::random(5),
            'ordre_redevance_fonciere' => now()->subDays(rand(1, 365)),
            'montant_ordre_redevance_fonciere' => 1005, //rand(1000, 5000)
            'cadre_id' => 2, //rand(1, 5)
            'observation_cotation_cadre' => 'Observation cotation cadre 6',
            'date_cotation_cadre' => now()->subDays(rand(1, 365)),
            'coter_csrcadastre' => now()->subDays(rand(1, 365)),
            'dos_tech_transmis_drm' => now()->subDays(rand(1, 365)),
            'dos_compl_csrdaf' => now()->subDays(rand(1, 365)),
            'cotation_compl_csrdaf' => now()->subDays(rand(1, 365)),
            'numero_serie' => 'NS-00006', //Str::random(5),
            'is_finalisation' => 'non',
            'is_complete' => 1, //rand(0, 1)
        ], [
            'uuid' => 07,
            'reference' => 'REF-00000007',
            'localisation' => 'Localisation 7',
            'region_id' => 7, // rand(1, 10)
            'division_id' => 7, // rand(1, 10)
            'sub_division_id' => 7, // rand(1, 10)
            'zone' => 'Zone 7',
            'etat_terrain' => 'Etat 7',
            'duplicata' => null,
            'source_terrain' => 'Source 7',
            'superficie' => 106, //rand(100, 1000)
            'volume' => 'Volume 7',
            'folio' => 'Folio 7',
            'numero_cp' => 'CP-00007',  //Str::random(5),
            'titre_foncier_id' => 7, //rand(1, 10)
            'numero_bordereau_transmission' => 'BT-00007', //Str::random(5),
            'next_step' => $steps[array_rand($steps)],
            'statut' => 'En cours',
            'StatutStyle' => 'primary',
            'date_delivrance' => now()->subDays(rand(1, 365)),
            'comissions' => json_encode(['Commission 7', 'Commission 8']),
            'service_id' => 4, //rand(1, 5)
            'cotation_user_id' => 4, //rand(1, 5)
            'observation_cotation' => 'Observation cotation 7',
            'date_cotation' => now()->subDays(rand(1, 365)),
            'status_cotation' => 'done',
            'montant_ordre_versement' => 1006, //rand(1000, 5000)
            'numero_ordre_versement' => 'OV-00007', //Str::random(5),
            'numero_arrete_ordre_versement' => 'AO-00007', //Str::random(5),
            'date_ordre_versement' => now()->subDays(rand(1, 365)),
            'status_ordre_versement' => 'done',
            'status_avis_publique' => 'done',
            'date_avis_publique' => now()->subDays(rand(1, 365)),
            'date_avis_publique_signe' => now()->subDays(rand(1, 365)),
            'calendar_decision' => 'Calendrier 7',
            'calendar_decision_date' => now()->subDays(rand(1, 365)),
            'date_debut_certificat_d_affichage' => now()->subDays(rand(1, 365)),
            'date_fin_certificat_d_affichage' => now()->subDays(rand(1, 365)),
            'date_certificat_d_affichage_signer' => now()->subDays(rand(1, 365)),
            'date_convocation' => now()->subDays(rand(1, 365)),
            'status_convocation' => 'Statut convocation 7',
            'geometre_id' => 4, //rand(1, 5)
            'date_geometre_enregistrer' => now()->subDays(rand(1, 365)),
            'pv_enregistrer' => now()->subDays(rand(1, 365)),
            'dossier_technique_complet' => now()->subDays(rand(1, 365)),
            'dossier_jumelage' => now()->subDays(rand(1, 365)),
            'transmission_csdaf' => now()->subDays(rand(1, 365)),
            'dossier_administratif_complet' => now()->subDays(rand(1, 365)),
            'dossier_technique_enregistrer' => now()->subDays(rand(1, 365)),
            'etat_cession_id' => 7, //rand(1, 10)
            'etat_cession' => now()->subDays(rand(1, 365)),
            'etat_cession_payer' => now()->subDays(rand(1, 365)),
            'date_publication_dossier_vise' => now()->subDays(rand(1, 365)),
            'date_signature_bulletin' => now()->subDays(rand(1, 365)),
            'coordonnees' => json_encode(['lat' => rand(0, 90), 'lng' => rand(0, 180)]),
            'limit_nord' => 'Nord 7',
            'limit_sud' => 'Sud 7',
            'limit_est' => 'Est 7',
            'limit_ouest' => 'Ouest 7',
            'dossier_technique_created' => now()->subDays(rand(1, 365)),
            'descente_terrain' => now()->subDays(rand(1, 365)),
            'transmission_dos_tech_csdaf' => now()->subDays(rand(1, 365)),
            'transmission_delegue_departemental' => now()->subDays(rand(1, 365)),
            'transmission_delegue_regional' => now()->subDays(rand(1, 365)),
            'date_calendrier_descente' => now()->subDays(rand(1, 365)),
            'service' => 'Service 7',
            'date_dossier_signe_csr_cadastre' => now()->subDays(rand(1, 365)),
            'date_dossier_transmi_au_Mindcaf' => now()->subDays(rand(1, 365)),
            'date_dossier_complet_transmi_CSRegional_mindcaf' => now()->subDays(rand(1, 365)),
            'date_dossier_vise_en_attente_publication' => now()->subDays(rand(1, 365)),
            'service_dossier_complet_id' => 4, //rand(1, 5)
            'user_dossier_complet_id' => 4, //rand(1, 5)
            'observation_dossier_complet' => 'Observation dossier complet 7',
            'date_dossier_complet_vise_coter' => now()->subDays(rand(1, 365)),
            'numero_redevance_fonciere' => 'RF-00007', //Str::random(5),
            'ordre_redevance_fonciere' => now()->subDays(rand(1, 365)),
            'montant_ordre_redevance_fonciere' => 1006, //rand(1000, 5000)
            'cadre_id' => 4, //rand(1, 5)
            'observation_cotation_cadre' => 'Observation cotation cadre 7',
            'date_cotation_cadre' => now()->subDays(rand(1, 365)),
            'coter_csrcadastre' => now()->subDays(rand(1, 365)),
            'dos_tech_transmis_drm' => now()->subDays(rand(1, 365)),
            'dos_compl_csrdaf' => now()->subDays(rand(1, 365)),
            'cotation_compl_csrdaf' => now()->subDays(rand(1, 365)),
            'numero_serie' => 'NS-00007', //Str::random(5),
            'is_finalisation' => 'non',
            'is_complete' => 0, //rand(0, 1)
        ], [
            'uuid' => 8,
            'reference' => 'REF-00000008',
            'localisation' => 'Localisation 8',
            'region_id' => 8, // rand(1, 10)
            'division_id' => 8, // rand(1, 10)
            'sub_division_id' => 8, // rand(1, 10)
            'zone' => 'Zone 8',
            'etat_terrain' => 'Etat 8',
            'duplicata' => null,
            'source_terrain' => 'Source 8',
            'superficie' => 107, //rand(100, 1000)
            'volume' => 'Volume 8',
            'folio' => 'Folio 8',
            'numero_cp' => 'CP-00008',  //Str::random(5),
            'titre_foncier_id' => 8, //rand(1, 10)
            'numero_bordereau_transmission' => 'BT-00008', //Str::random(5),
            'next_step' => $steps[array_rand($steps)],
            'statut' => 'En cours',
            'StatutStyle' => 'primary',
            'date_delivrance' => now()->subDays(rand(1, 365)),
            'comissions' => json_encode(['Commission 8', 'Commission 9']),
            'service_id' => 5, //rand(1, 5)
            'cotation_user_id' => 8, //rand(1, 5)
            'observation_cotation' => 'Observation cotation 8',
            'date_cotation' => now()->subDays(rand(1, 365)),
            'status_cotation' => 'done',
            'montant_ordre_versement' => 1007, //rand(1000, 5000)
            'numero_ordre_versement' => 'OV-00008', //Str::random(5),
            'numero_arrete_ordre_versement' => 'AO-00008', //Str::random(5),
            'date_ordre_versement' => now()->subDays(rand(1, 365)),
            'status_ordre_versement' => 'done',
            'status_avis_publique' => 'done',
            'date_avis_publique' => now()->subDays(rand(1, 365)),
            'date_avis_publique_signe' => now()->subDays(rand(1, 365)),
            'calendar_decision' => 'Calendrier 8',
            'calendar_decision_date' => now()->subDays(rand(1, 365)),
            'date_debut_certificat_d_affichage' => now()->subDays(rand(1, 365)),
            'date_fin_certificat_d_affichage' => now()->subDays(rand(1, 365)),
            'date_certificat_d_affichage_signer' => now()->subDays(rand(1, 365)),
            'date_convocation' => now()->subDays(rand(1, 365)),
            'status_convocation' => 'Statut convocation 8',
            'geometre_id' => 5, //rand(1, 5)
            'date_geometre_enregistrer' => now()->subDays(rand(1, 365)),
            'pv_enregistrer' => now()->subDays(rand(1, 365)),
            'dossier_technique_complet' => now()->subDays(rand(1, 365)),
            'dossier_jumelage' => now()->subDays(rand(1, 365)),
            'transmission_csdaf' => now()->subDays(rand(1, 365)),
            'dossier_administratif_complet' => now()->subDays(rand(1, 365)),
            'dossier_technique_enregistrer' => now()->subDays(rand(1, 365)),
            'etat_cession_id' => 8, //rand(1, 10)
            'etat_cession' => now()->subDays(rand(1, 365)),
            'etat_cession_payer' => now()->subDays(rand(1, 365)),
            'date_publication_dossier_vise' => now()->subDays(rand(1, 365)),
            'date_signature_bulletin' => now()->subDays(rand(1, 365)),
            'coordonnees' => json_encode(['lat' => rand(0, 90), 'lng' => rand(0, 180)]),
            'limit_nord' => 'Nord 8',
            'limit_sud' => 'Sud 8',
            'limit_est' => 'Est 8',
            'limit_ouest' => 'Ouest 8',
            'dossier_technique_created' => now()->subDays(rand(1, 365)),
            'descente_terrain' => now()->subDays(rand(1, 365)),
            'transmission_dos_tech_csdaf' => now()->subDays(rand(1, 365)),
            'transmission_delegue_departemental' => now()->subDays(rand(1, 365)),
            'transmission_delegue_regional' => now()->subDays(rand(1, 365)),
            'date_calendrier_descente' => now()->subDays(rand(1, 365)),
            'service' => 'Service 8',
            'date_dossier_signe_csr_cadastre' => now()->subDays(rand(1, 365)),
            'date_dossier_transmi_au_Mindcaf' => now()->subDays(rand(1, 365)),
            'date_dossier_complet_transmi_CSRegional_mindcaf' => now()->subDays(rand(1, 365)),
            'date_dossier_vise_en_attente_publication' => now()->subDays(rand(1, 365)),
            'service_dossier_complet_id' => 5, //rand(1, 5)
            'user_dossier_complet_id' => 5, //rand(1, 5)
            'observation_dossier_complet' => 'Observation dossier complet 8',
            'date_dossier_complet_vise_coter' => now()->subDays(rand(1, 365)),
            'numero_redevance_fonciere' => 'RF-00008', //Str::random(5),
            'ordre_redevance_fonciere' => now()->subDays(rand(1, 365)),
            'montant_ordre_redevance_fonciere' => 1007, //rand(1000, 5000)
            'cadre_id' => 5, //rand(1, 5)
            'observation_cotation_cadre' => 'Observation cotation cadre 8',
            'date_cotation_cadre' => now()->subDays(rand(1, 365)),
            'coter_csrcadastre' => now()->subDays(rand(1, 365)),
            'dos_tech_transmis_drm' => now()->subDays(rand(1, 365)),
            'dos_compl_csrdaf' => now()->subDays(rand(1, 365)),
            'cotation_compl_csrdaf' => now()->subDays(rand(1, 365)),
            'numero_serie' => 'NS-00008', //Str::random(5),
            'is_finalisation' => 'non',
            'is_complete' => 0, //rand(0, 1)
        ], [
            'uuid' => 9,
            'reference' => 'REF-00000009',
            'localisation' => 'Localisation 9',
            'region_id' => 9, // rand(1, 10)
            'division_id' => 9, // rand(1, 10)
            'sub_division_id' => 9, // rand(1, 10)
            'zone' => 'Zone 9',
            'etat_terrain' => 'Etat 9',
            'duplicata' => null,
            'source_terrain' => 'Source 9',
            'superficie' => 108, //rand(100, 1000)
            'volume' => 'Volume 9',
            'folio' => 'Folio 9',
            'numero_cp' => 'CP-00009',  //Str::random(5),
            'titre_foncier_id' => 9, //rand(1, 10)
            'numero_bordereau_transmission' => 'BT-00009', //Str::random(5),
            'next_step' => $steps[array_rand($steps)],
            'statut' => 'En cours',
            'StatutStyle' => 'primary',
            'date_delivrance' => now()->subDays(rand(1, 365)),
            'comissions' => json_encode(['Commission 9', 'Commission 10']),
            'service_id' => 1, //rand(1, 5)
            'cotation_user_id' => 1, //rand(1, 5)
            'observation_cotation' => 'Observation cotation 9',
            'date_cotation' => now()->subDays(rand(1, 365)),
            'status_cotation' => 'done',
            'montant_ordre_versement' => 1008, //rand(1000, 5000)
            'numero_ordre_versement' => 'OV-00009', //Str::random(5),
            'numero_arrete_ordre_versement' => 'AO-00009', //Str::random(5),
            'date_ordre_versement' => now()->subDays(rand(1, 365)),
            'status_ordre_versement' => 'done',
            'status_avis_publique' => 'done',
            'date_avis_publique' => now()->subDays(rand(1, 365)),
            'date_avis_publique_signe' => now()->subDays(rand(1, 365)),
            'calendar_decision' => 'Calendrier 9',
            'calendar_decision_date' => now()->subDays(rand(1, 365)),
            'date_debut_certificat_d_affichage' => now()->subDays(rand(1, 365)),
            'date_fin_certificat_d_affichage' => now()->subDays(rand(1, 365)),
            'date_certificat_d_affichage_signer' => now()->subDays(rand(1, 365)),
            'date_convocation' => now()->subDays(rand(1, 365)),
            'status_convocation' => 'Statut convocation 9',
            'geometre_id' => 1, //rand(1, 5)
            'date_geometre_enregistrer' => now()->subDays(rand(1, 365)),
            'pv_enregistrer' => now()->subDays(rand(1, 365)),
            'dossier_technique_complet' => now()->subDays(rand(1, 365)),
            'dossier_jumelage' => now()->subDays(rand(1, 365)),
            'transmission_csdaf' => now()->subDays(rand(1, 365)),
            'dossier_administratif_complet' => now()->subDays(rand(1, 365)),
            'dossier_technique_enregistrer' => now()->subDays(rand(1, 365)),
            'etat_cession_id' => 9, //rand(1, 10)
            'etat_cession' => now()->subDays(rand(1, 365)),
            'etat_cession_payer' => now()->subDays(rand(1, 365)),
            'date_publication_dossier_vise' => now()->subDays(rand(1, 365)),
            'date_signature_bulletin' => now()->subDays(rand(1, 365)),
            'coordonnees' => json_encode(['lat' => rand(0, 90), 'lng' => rand(0, 180)]),
            'limit_nord' => 'Nord 9',
            'limit_sud' => 'Sud 9',
            'limit_est' => 'Est 9',
            'limit_ouest' => 'Ouest 9',
            'dossier_technique_created' => now()->subDays(rand(1, 365)),
            'descente_terrain' => now()->subDays(rand(1, 365)),
            'transmission_dos_tech_csdaf' => now()->subDays(rand(1, 365)),
            'transmission_delegue_departemental' => now()->subDays(rand(1, 365)),
            'transmission_delegue_regional' => now()->subDays(rand(1, 365)),
            'date_calendrier_descente' => now()->subDays(rand(1, 365)),
            'service' => 'Service 9',
            'date_dossier_signe_csr_cadastre' => now()->subDays(rand(1, 365)),
            'date_dossier_transmi_au_Mindcaf' => now()->subDays(rand(1, 365)),
            'date_dossier_complet_transmi_CSRegional_mindcaf' => now()->subDays(rand(1, 365)),
            'date_dossier_vise_en_attente_publication' => now()->subDays(rand(1, 365)),
            'service_dossier_complet_id' => 1, //rand(1, 5)
            'user_dossier_complet_id' => 1, //rand(1, 5)
            'observation_dossier_complet' => 'Observation dossier complet 9',
            'date_dossier_complet_vise_coter' => now()->subDays(rand(1, 365)),
            'numero_redevance_fonciere' => 'RF-00009', //Str::random(5),
            'ordre_redevance_fonciere' => now()->subDays(rand(1, 365)),
            'montant_ordre_redevance_fonciere' => 1008, //rand(1000, 5000)
            'cadre_id' => 1, //rand(1, 5)
            'observation_cotation_cadre' => 'Observation cotation cadre 9',
            'date_cotation_cadre' => now()->subDays(rand(1, 365)),
            'coter_csrcadastre' => now()->subDays(rand(1, 365)),
            'dos_tech_transmis_drm' => now()->subDays(rand(1, 365)),
            'dos_compl_csrdaf' => now()->subDays(rand(1, 365)),
            'cotation_compl_csrdaf' => now()->subDays(rand(1, 365)),
            'numero_serie' => 'NS-00009', //Str::random(5),
            'is_finalisation' => 'non',
            'is_complete' => 1, //rand(0, 1)
        ], [
            'uuid' => 10,
            'reference' => 'REF-000000010',
            'localisation' => 'Localisation 10',
            'region_id' => 10, // rand(1, 10)
            'division_id' => 10, // rand(1, 10)
            'sub_division_id' => 10, // rand(1, 10)
            'zone' => 'Zone 10',
            'etat_terrain' => 'Etat 10',
            'duplicata' => null,
            'source_terrain' => 'Source 10',
            'superficie' => 109, //rand(100, 1000)
            'volume' => 'Volume 10',
            'folio' => 'Folio 10',
            'numero_cp' => 'CP-000010',  //Str::random(5),
            'titre_foncier_id' => 10, //rand(1, 10)
            'numero_bordereau_transmission' => 'BT-000010', //Str::random(5),
            'next_step' => $steps[array_rand($steps)],
            'statut' => 'En cours',
            'StatutStyle' => 'primary',
            'date_delivrance' => now()->subDays(rand(1, 365)),
            'comissions' => json_encode(['Commission 10', 'Commission 11']),
            'service_id' => 2, //rand(1, 5)
            'cotation_user_id' => 2, //rand(1, 5)
            'observation_cotation' => 'Observation cotation 10',
            'date_cotation' => now()->subDays(rand(1, 365)),
            'status_cotation' => 'done',
            'montant_ordre_versement' => 1009, //rand(1000, 5000)
            'numero_ordre_versement' => 'OV-000010', //Str::random(5),
            'numero_arrete_ordre_versement' => 'AO-000010', //Str::random(5),
            'date_ordre_versement' => now()->subDays(rand(1, 365)),
            'status_ordre_versement' => 'done',
            'status_avis_publique' => 'done',
            'date_avis_publique' => now()->subDays(rand(1, 365)),
            'date_avis_publique_signe' => now()->subDays(rand(1, 365)),
            'calendar_decision' => 'Calendrier 10',
            'calendar_decision_date' => now()->subDays(rand(1, 365)),
            'date_debut_certificat_d_affichage' => now()->subDays(rand(1, 365)),
            'date_fin_certificat_d_affichage' => now()->subDays(rand(1, 365)),
            'date_certificat_d_affichage_signer' => now()->subDays(rand(1, 365)),
            'date_convocation' => now()->subDays(rand(1, 365)),
            'status_convocation' => 'Statut convocation 10',
            'geometre_id' => 2, //rand(1, 5)
            'date_geometre_enregistrer' => now()->subDays(rand(1, 365)),
            'pv_enregistrer' => now()->subDays(rand(1, 365)),
            'dossier_technique_complet' => now()->subDays(rand(1, 365)),
            'dossier_jumelage' => now()->subDays(rand(1, 365)),
            'transmission_csdaf' => now()->subDays(rand(1, 365)),
            'dossier_administratif_complet' => now()->subDays(rand(1, 365)),
            'dossier_technique_enregistrer' => now()->subDays(rand(1, 365)),
            'etat_cession_id' => 10, //rand(1, 10)
            'etat_cession' => now()->subDays(rand(1, 365)),
            'etat_cession_payer' => now()->subDays(rand(1, 365)),
            'date_publication_dossier_vise' => now()->subDays(rand(1, 365)),
            'date_signature_bulletin' => now()->subDays(rand(1, 365)),
            'coordonnees' => json_encode(['lat' => rand(0, 90), 'lng' => rand(0, 180)]),
            'limit_nord' => 'Nord 10',
            'limit_sud' => 'Sud 10',
            'limit_est' => 'Est 10',
            'limit_ouest' => 'Ouest 10',
            'dossier_technique_created' => now()->subDays(rand(1, 365)),
            'descente_terrain' => now()->subDays(rand(1, 365)),
            'transmission_dos_tech_csdaf' => now()->subDays(rand(1, 365)),
            'transmission_delegue_departemental' => now()->subDays(rand(1, 365)),
            'transmission_delegue_regional' => now()->subDays(rand(1, 365)),
            'date_calendrier_descente' => now()->subDays(rand(1, 365)),
            'service' => 'Service 10',
            'date_dossier_signe_csr_cadastre' => now()->subDays(rand(1, 365)),
            'date_dossier_transmi_au_Mindcaf' => now()->subDays(rand(1, 365)),
            'date_dossier_complet_transmi_CSRegional_mindcaf' => now()->subDays(rand(1, 365)),
            'date_dossier_vise_en_attente_publication' => now()->subDays(rand(1, 365)),
            'service_dossier_complet_id' => 2, //rand(1, 5)
            'user_dossier_complet_id' => 2, //rand(1, 5)
            'observation_dossier_complet' => 'Observation dossier complet 10',
            'date_dossier_complet_vise_coter' => now()->subDays(rand(1, 365)),
            'numero_redevance_fonciere' => 'RF-000010', //Str::random(5),
            'ordre_redevance_fonciere' => now()->subDays(rand(1, 365)),
            'montant_ordre_redevance_fonciere' => 1009, //rand(1000, 5000)
            'cadre_id' => 2, //rand(1, 5)
            'observation_cotation_cadre' => 'Observation cotation cadre 10',
            'date_cotation_cadre' => now()->subDays(rand(1, 365)),
            'coter_csrcadastre' => now()->subDays(rand(1, 365)),
            'dos_tech_transmis_drm' => now()->subDays(rand(1, 365)),
            'dos_compl_csrdaf' => now()->subDays(rand(1, 365)),
            'cotation_compl_csrdaf' => now()->subDays(rand(1, 365)),
            'numero_serie' => 'NS-000010', //Str::random(5),
            'is_finalisation' => 'non',
            'is_complete' => 0, //rand(0, 1)
        ]];

        foreach($elements as $element){
            ImmatriculationDirecte::create($element);
        }
        
        
        $immatriculations = ImmatriculationDirecte::all();
        $users = User::all();

        foreach ($immatriculations as $immatriculation) {
            // Associe aléatoirement entre 1 et 3 utilisateurs à chaque immatriculation_directe
            $userIds = $users->random(rand(1, 3))->pluck('id');

            foreach ($userIds as $userId) {
                DB::table('immatriculation_directe_user')->insert([
                    'immatriculation_directe_id' => $immatriculation->id,
                    'user_id' => $userId,
                    'created_at' => now(),
                    'updated_at' => now(),
                ]);
            }
        }
    }
}
