<?php

namespace Database\Seeders;

use App\Models\Region;
use App\Models\Division;
use App\Models\SubDivision;
use Illuminate\Support\Str;
use App\Models\TitreFoncier;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Support\Facades\DB;
use App\Models\User;
use Spatie\Permission\Models\Role;
use Illuminate\Support\Collection;
use proj4php\Proj4php;
use proj4php\Proj;
use proj4php\Point;

class TitreFoncierSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function convert($utmCoordinates)
    {
        // Initialisez Proj4
        $proj4 = new Proj4php();

        // Créez les projections
        $projUTM = new Proj('+proj=utm +zone=32 +datum=WGS84 +units=m +no_defs', $proj4);
        $projWGS84 = new Proj('EPSG:4326', $proj4);

        $decimalResults = [];

        foreach ($utmCoordinates as $utm) {
            $utmParts = explode(',', $utm); // Sépare les coordonnées UTM en X et Y
            $utmX = floatval($utmParts[0]);
            $utmY = floatval($utmParts[1]);

            // Créez le point source avec les coordonnées UTM
            $pointSrc = new Point($utmX, $utmY, $projUTM);

            // Transformez le point entre les systèmes de coordonnées
            $pointDest = $proj4->transform($projWGS84, $pointSrc);

            // Obtenez les coordonnées lat/lon du point de destination
            $lat = $pointDest->y;
            $lon = $pointDest->x;

            // Ajoutez le résultat à votre tableau de résultats en coordonnées décimales
            $decimalResults[] = "$lon, $lat";
        }

        return $decimalResults;
    }
    public function run(): void
    {
        TitreFoncier::flushEventListeners();


        // Récupérer les IDs des utilisateurs et des titres fonciers
        $users = DB::table('users')->pluck('id');
        $titresFoncier = DB::table('titre_fonciers')->pluck('id');

        // Convertir les IDs en collections pour faciliter les opérations
        $usersCollection = $users instanceof Collection ? $users : collect($users);
        $titresFoncierCollection = $titresFoncier instanceof Collection ? $titresFoncier : collect($titresFoncier);

        // Créer un tableau d'associations
        $associations = [];

        // Associer les titres fonciers aux utilisateurs
        foreach ($usersCollection as $userId) {
            // Vérifier que l'utilisateur existe dans la collection
            if ($usersCollection->contains($userId)) {
                // Prendre 5 titres fonciers aléatoires pour chaque utilisateur
                $randomTitles = $titresFoncierCollection->random(min(5, $titresFoncierCollection->count()));
                foreach ($randomTitles as $titleId) {
                    // Vérifier que le titre foncier existe dans la collection
                    if ($titresFoncierCollection->contains($titleId)) {
                        $associations[] = ['titre_foncier_id' => $titleId, 'user_id' => $userId];
                    }
                }
            }
        }

        // Insérer les données dans la table titrefoncier_user
        if (!empty($associations)) {
            DB::table('titrefoncier_user')->insert($associations);
        }

        $coordinates = [
            ["604588.9956404036, 1283523.1884052807", "604479.3739269332, 1283505.014106314", "604467.5203713928, 1283560.7118539717"],
            ["585950, 444731", "586077, 444748", "585978, 444525", "586135,444537"],
            ["627668.6068432052, 1025765.4931505624", "627831.950875392, 1025767.1336289607", "627889.9783554913,1025993.906016382"]
        ];



           TitreFoncier::create([
                'uuid' => Str::uuid(),
                'numero_titre_foncier' => "CE/CE10/A/1",
                'date_de_delivrance_du_TF' => '2023-01-01',
                'numero_du_duplicata' => 1,
                'region_id' => Region::where('id', 2)->first()->id,
                'division_id' => Division::where('id', 10)->first()->id,
                'sub_division_id' => SubDivision::where('id', 59)->first()->id,
                'groupement' => '',
                'lieu_dit' => 'Mambila' ,
                'zone'=>'urbain',
                'numero_folio' => '1' ,
                'volume' => '1' ,
                'superficie_du_TF_mere' => 4000 ,
                'etat_terrain' => 'non_batit',
                'provenance_TF' => 'mutation_totale',
                'numero_bordereau_analytique' => '1',
                'coordonnees' => json_encode($this->convert($coordinates[0])),
                'coordonnees_utm' => json_encode($coordinates[0]),
                'limit_nord' => 'route' ,
                'limit_sud' => 'route',
                'limit_est' => 'route',
                'limit_ouest' => 'route',
            ]);
            TitreFoncier::create([
                'uuid' => Str::uuid(),
                'numero_titre_foncier' => "LT/LT26/A/2",
                'date_de_delivrance_du_TF' => '2023-01-01',
                'numero_du_duplicata' => 1,
                'region_id' => Region::where('id', 5)->first()->id,
                'division_id' => Division::where('id', 26)->first()->id,
                'sub_division_id' => SubDivision::where('id', 170)->first()->id,
                'groupement' => '',
                'lieu_dit' => 'Mambila' ,
                'zone'=>'urbain',
                'numero_folio' => '1' ,
                'volume' => '1' ,
                'superficie_du_TF_mere' => 4000 ,
                'etat_terrain' => 'non_batit',
                'provenance_TF' => 'mutation_totale',
                'numero_bordereau_analytique' => '1',
                'coordonnees' => json_encode($this->convert($coordinates[1])),
                'coordonnees_utm' => json_encode($coordinates[1]),
                'limit_nord' => 'route' ,
                'limit_sud' => 'route',
                'limit_est' => 'route',
                'limit_ouest' => 'route',
            ]);
            TitreFoncier::create([
                'uuid' => Str::uuid(),
                'numero_titre_foncier' => Str::random(11),
                'date_de_delivrance_du_TF' => '2023-01-01',
                'numero_du_duplicata' => 1,
                'region_id' => Region::where('id', 10)->first()->id,
                'division_id' => Division::where('id', 53)->first()->id,
                'sub_division_id' => SubDivision::where('id', 322)->first()->id,
                'groupement' => '',
                'lieu_dit' => 'Mambila' ,
                'zone'=>'urbain',
                'numero_folio' => '1' ,
                'volume' => '1' ,
                'superficie_du_TF_mere' => 4000 ,
                'etat_terrain' => 'non_batit',
                'provenance_TF' => 'mutation_totale',
                'numero_bordereau_analytique' => '1',
                'coordonnees' => json_encode($this->convert($coordinates[2])),
                'coordonnees_utm' => json_encode($coordinates[2]),
                'limit_nord' => 'route' ,
                'limit_sud' => 'route',
                'limit_est' => 'route',
                'limit_ouest' => 'route',
            ]);
            TitreFoncier::create([
                'uuid' => Str::uuid(),
                'numero_titre_foncier' => Str::random(11),
                'date_de_delivrance_du_TF' => '2023-01-01',
                'numero_du_duplicata' => 1,
                'region_id' => Region::where('id', 1)->first()->id,
                'division_id' => Division::where('id', 2)->first()->id,
                'sub_division_id' => SubDivision::where('id', 4)->first()->id,
                'groupement' => '',
                'lieu_dit' => 'Mambila' ,
                'zone'=>'urbain',
                'numero_folio' => '1' ,
                'volume' => '1' ,
                'superficie_du_TF_mere' => 4000 ,
                'etat_terrain' => 'non_batit',
                'provenance_TF' => 'mutation_totale',
                'numero_bordereau_analytique' => '1',
                'coordonnees' => json_encode($coordinates[0]),
                'limit_nord' => 'route' ,
                'limit_sud' => 'route',
                'limit_est' => 'route',
                'limit_ouest' => 'route',
            ]);
            TitreFoncier::create([
                'uuid' => Str::uuid(),
                'numero_titre_foncier' => Str::random(11),
                'date_de_delivrance_du_TF' => '2023-01-01',
                'numero_du_duplicata' => 1,
                'region_id' => Region::where('id', 1)->first()->id,
                'division_id' => Division::where('id', 2)->first()->id,
                'sub_division_id' => SubDivision::where('id', 5)->first()->id,
                'groupement' => '',
                'lieu_dit' => 'Mambila' ,
                'zone'=>'urbain',
                'numero_folio' => '1' ,
                'volume' => '1' ,
                'superficie_du_TF_mere' => 4000 ,
                'etat_terrain' => 'non_batit',
                'provenance_TF' => 'mutation_totale',
                'numero_bordereau_analytique' => '1',
                'coordonnees' => json_encode($coordinates[0]),
                'limit_nord' => 'route' ,
                'limit_sud' => 'route',
                'limit_est' => 'route',
                'limit_ouest' => 'route',
            ]);
            TitreFoncier::create([
                'uuid' => Str::uuid(),
                'numero_titre_foncier' => Str::random(11),
                'date_de_delivrance_du_TF' => '2023-01-01',
                'numero_du_duplicata' => 1,
                'region_id' => Region::where('id', 1)->first()->id,
                'division_id' => Division::where('id', 3)->first()->id,
                'sub_division_id' => SubDivision::where('id', 6)->first()->id,
                'groupement' => '',
                'lieu_dit' => 'Mambila' ,
                'zone'=>'urbain',
                'numero_folio' => '1' ,
                'volume' => '1' ,
                'superficie_du_TF_mere' => 4000 ,
                'etat_terrain' => 'non_batit',
                'provenance_TF' => 'mutation_totale',
                'numero_bordereau_analytique' => '1',
                'coordonnees' => json_encode($coordinates[0]),
                'limit_nord' => 'route' ,
                'limit_sud' => 'route',
                'limit_est' => 'route',
                'limit_ouest' => 'route',
            ]);
            TitreFoncier::create([
                'uuid' => Str::uuid(),
                'numero_titre_foncier' => Str::random(11),
                'date_de_delivrance_du_TF' => '2023-01-01',
                'numero_du_duplicata' => 1,
                'region_id' => Region::where('id', 1)->first()->id,
                'division_id' => Division::where('id', 3)->first()->id,
                'sub_division_id' => SubDivision::where('id', 7)->first()->id,
                'groupement' => '',
                'lieu_dit' => 'Mambila' ,
                'zone'=>'urbain',
                'numero_folio' => '1' ,
                'volume' => '1' ,
                'superficie_du_TF_mere' => 4000 ,
                'etat_terrain' => 'non_batit',
                'provenance_TF' => 'mutation_totale',
                'numero_bordereau_analytique' => '1',
                'coordonnees' => json_encode($coordinates[0]),
                'limit_nord' => 'route' ,
                'limit_sud' => 'route',
                'limit_est' => 'route',
                'limit_ouest' => 'route',
            ]);
            TitreFoncier::create([
                'uuid' => Str::uuid(),
                'numero_titre_foncier' => Str::random(11),
                'date_de_delivrance_du_TF' => '2023-01-01',
                'numero_du_duplicata' => 1,
                'region_id' => Region::where('id', 1)->first()->id,
                'division_id' => Division::where('id', 4)->first()->id,
                'sub_division_id' => SubDivision::where('id', 10)->first()->id,
                'groupement' => '',
                'lieu_dit' => 'Mambila' ,
                'zone'=>'urbain',
                'numero_folio' => '1' ,
                'volume' => '1' ,
                'superficie_du_TF_mere' => 4000 ,
                'etat_terrain' => 'non_batit',
                'provenance_TF' => 'mutation_totale',
                'numero_bordereau_analytique' => '1',
                'coordonnees' => json_encode($coordinates[0]),
                'limit_nord' => 'route' ,
                'limit_sud' => 'route',
                'limit_est' => 'route',
                'limit_ouest' => 'route',
            ]);
            TitreFoncier::create([
                'uuid' => Str::uuid(),
                'numero_titre_foncier' => Str::random(11),
                'date_de_delivrance_du_TF' => '2023-01-01',
                'numero_du_duplicata' => 1,
                'region_id' => Region::where('id', 1)->first()->id,
                'division_id' => Division::where('id', 4)->first()->id,
                'sub_division_id' => SubDivision::where('id', 11)->first()->id,
                'groupement' => '',
                'lieu_dit' => 'Mambila' ,
                'zone'=>'urbain',
                'numero_folio' => '1' ,
                'volume' => '1' ,
                'superficie_du_TF_mere' => 4000 ,
                'etat_terrain' => 'non_batit',
                'provenance_TF' => 'mutation_totale',
                'numero_bordereau_analytique' => '1',
                'coordonnees' => json_encode($coordinates[0]),
                'limit_nord' => 'route' ,
                'limit_sud' => 'route',
                'limit_est' => 'route',
                'limit_ouest' => 'route',
            ]);
            TitreFoncier::create([
                'uuid' => Str::uuid(),
                'numero_titre_foncier' => Str::random(11),
                'date_de_delivrance_du_TF' => '2023-01-01',
                'numero_du_duplicata' => 1,
                'region_id' => Region::where('id', 1)->first()->id,
                'division_id' => Division::where('id', 5)->first()->id,
                'sub_division_id' => SubDivision::where('id', 14)->first()->id,
                'groupement' => '',
                'lieu_dit' => 'Mambila' ,
                'zone'=>'urbain',
                'numero_folio' => '1' ,
                'volume' => '1' ,
                'superficie_du_TF_mere' => 4000 ,
                'etat_terrain' => 'non_batit',
                'provenance_TF' => 'mutation_totale',
                'numero_bordereau_analytique' => '1',
                'coordonnees' => json_encode($coordinates[0]),
                'limit_nord' => 'route' ,
                'limit_sud' => 'route',
                'limit_est' => 'route',
                'limit_ouest' => 'route',
            ]);
            TitreFoncier::create([
                'uuid' => Str::uuid(),
                'numero_titre_foncier' => Str::random(11),
                'date_de_delivrance_du_TF' => '2023-01-01',
                'numero_du_duplicata' => 1,
                'region_id' => Region::where('id', 2)->first()->id,
                'division_id' => Division::where('id', 6)->first()->id,
                'sub_division_id' => SubDivision::where('id', 22)->first()->id,
                'groupement' => '',
                'lieu_dit' => 'Mambila' ,
                'zone'=>'urbain',
                'numero_folio' => '1' ,
                'volume' => '1' ,
                'superficie_du_TF_mere' => 4000 ,
                'etat_terrain' => 'non_batit',
                'provenance_TF' => 'mutation_totale',
                'numero_bordereau_analytique' => '1',
                'coordonnees' => json_encode($coordinates[0]),
                'limit_nord' => 'route' ,
                'limit_sud' => 'route',
                'limit_est' => 'route',
                'limit_ouest' => 'route',
            ]);
            TitreFoncier::create([
                'uuid' => Str::uuid(),
                'numero_titre_foncier' => Str::random(11),
                'date_de_delivrance_du_TF' => '2023-01-01',
                'numero_du_duplicata' => 1,
                'region_id' => Region::where('id', 2)->first()->id,
                'division_id' => Division::where('id', 7)->first()->id,
                'sub_division_id' => SubDivision::where('id', 29)->first()->id,
                'groupement' => '',
                'lieu_dit' => 'Mambila' ,
                'zone'=>'urbain',
                'numero_folio' => '1' ,
                'volume' => '1' ,
                'superficie_du_TF_mere' => 4000 ,
                'etat_terrain' => 'non_batit',
                'provenance_TF' => 'mutation_totale',
                'numero_bordereau_analytique' => '1',
                'coordonnees' => json_encode($coordinates[0]),
                'limit_nord' => 'route' ,
                'limit_sud' => 'route',
                'limit_est' => 'route',
                'limit_ouest' => 'route',
            ]);
            TitreFoncier::create([
                'uuid' => Str::uuid(),
                'numero_titre_foncier' => Str::random(11),
                'date_de_delivrance_du_TF' => '2022-01-01',
                'numero_du_duplicata' => 1,
                'region_id' => Region::where('id', 2)->first()->id,
                'division_id' => Division::where('id', 7)->first()->id,
                'sub_division_id' => SubDivision::where('id', 29)->first()->id,
                'groupement' => '',
                'lieu_dit' => 'Mambila' ,
                'zone'=>'urbain',
                'numero_folio' => '1' ,
                'volume' => '1' ,
                'superficie_du_TF_mere' => 4000 ,
                'etat_terrain' => 'non_batit',
                'provenance_TF' => 'mutation_totale',
                'numero_bordereau_analytique' => '1',
                'coordonnees' => json_encode($coordinates[0]),
                'limit_nord' => 'route' ,
                'limit_sud' => 'route',
                'limit_est' => 'route',
                'limit_ouest' => 'route',
            ]);
            TitreFoncier::create([
                'uuid' => Str::uuid(),
                'numero_titre_foncier' => Str::random(11),
                'date_de_delivrance_du_TF' => '2022-01-01',
                'numero_du_duplicata' => 1,
                'region_id' => Region::where('id', 2)->first()->id,
                'division_id' => Division::where('id', 8)->first()->id,
                'sub_division_id' => SubDivision::where('id', 38)->first()->id,
                'groupement' => '',
                'lieu_dit' => 'Mambila' ,
                'zone'=>'urbain',
                'numero_folio' => '1' ,
                'volume' => '1' ,
                'superficie_du_TF_mere' => 4000 ,
                'etat_terrain' => 'non_batit',
                'provenance_TF' => 'mutation_totale',
                'numero_bordereau_analytique' => '1',
                'coordonnees' => json_encode($coordinates[0]),
                'limit_nord' => 'route' ,
                'limit_sud' => 'route',
                'limit_est' => 'route',
                'limit_ouest' => 'route',
            ]);
            TitreFoncier::create([
                'uuid' => Str::uuid(),
                'numero_titre_foncier' => Str::random(11),
                'date_de_delivrance_du_TF' => '2022-01-01',
                'numero_du_duplicata' => 1,
                'region_id' => Region::where('id', 2)->first()->id,
                'division_id' => Division::where('id', 8)->first()->id,
                'sub_division_id' => SubDivision::where('id', 39)->first()->id,
                'groupement' => '',
                'lieu_dit' => 'Mambila' ,
                'zone'=>'urbain',
                'numero_folio' => '1' ,
                'volume' => '1' ,
                'superficie_du_TF_mere' => 4000 ,
                'etat_terrain' => 'non_batit',
                'provenance_TF' => 'mutation_totale',
                'numero_bordereau_analytique' => '1',
                'coordonnees' => json_encode($coordinates[0]),
                'limit_nord' => 'route' ,
                'limit_sud' => 'route',
                'limit_est' => 'route',
                'limit_ouest' => 'route',
            ]);
            TitreFoncier::create([
                'uuid' => Str::uuid(),
                'numero_titre_foncier' => Str::random(11),
                'date_de_delivrance_du_TF' => '2022-01-01',
                'numero_du_duplicata' => 1,
                'region_id' => Region::where('id', 2)->first()->id,
                'division_id' => Division::where('id', 9)->first()->id,
                'sub_division_id' => SubDivision::where('id', 47)->first()->id,
                'groupement' => '',
                'lieu_dit' => 'Mambila' ,
                'zone'=>'urbain',
                'numero_folio' => '1' ,
                'volume' => '1' ,
                'superficie_du_TF_mere' => 4000 ,
                'etat_terrain' => 'non_batit',
                'provenance_TF' => 'mutation_totale',
                'numero_bordereau_analytique' => '1',
                'coordonnees' => json_encode($coordinates[0]),
                'limit_nord' => 'route' ,
                'limit_sud' => 'route',
                'limit_est' => 'route',
                'limit_ouest' => 'route',
            ]);
            TitreFoncier::create([
                'uuid' => Str::uuid(),
                'numero_titre_foncier' => Str::random(11),
                'date_de_delivrance_du_TF' => '2022-01-01',
                'numero_du_duplicata' => 1,
                'region_id' => Region::where('id', 2)->first()->id,
                'division_id' => Division::where('id', 9)->first()->id,
                'sub_division_id' => SubDivision::where('id', 48)->first()->id,
                'groupement' => '',
                'lieu_dit' => 'Mambila' ,
                'zone'=>'urbain',
                'numero_folio' => '1' ,
                'volume' => '1' ,
                'superficie_du_TF_mere' => 4000 ,
                'etat_terrain' => 'non_batit',
                'provenance_TF' => 'mutation_totale',
                'numero_bordereau_analytique' => '1',
                'coordonnees' => json_encode($coordinates[0]),
                'limit_nord' => 'route' ,
                'limit_sud' => 'route',
                'limit_est' => 'route',
                'limit_ouest' => 'route',
            ]);
            TitreFoncier::create([
                'uuid' => Str::uuid(),
                'numero_titre_foncier' => Str::random(11),
                'date_de_delivrance_du_TF' => '2022-01-01',
                'numero_du_duplicata' => 1,
                'region_id' => Region::where('id', 2)->first()->id,
                'division_id' => Division::where('id', 10)->first()->id,
                'sub_division_id' => SubDivision::where('id', 52)->first()->id,
                'groupement' => '',
                'lieu_dit' => 'Mambila' ,
                'zone'=>'urbain',
                'numero_folio' => '1' ,
                'volume' => '1' ,
                'superficie_du_TF_mere' => 4000 ,
                'etat_terrain' => 'non_batit',
                'provenance_TF' => 'mutation_totale',
                'numero_bordereau_analytique' => '1',
                'coordonnees' => json_encode($coordinates[0]),
                'limit_nord' => 'route' ,
                'limit_sud' => 'route',
                'limit_est' => 'route',
                'limit_ouest' => 'route',
            ]);
            TitreFoncier::create([
                'uuid' => Str::uuid(),
                'numero_titre_foncier' => Str::random(11),
                'date_de_delivrance_du_TF' => '2022-01-01',
                'numero_du_duplicata' => 1,
                'region_id' => Region::where('id', 2)->first()->id,
                'division_id' => Division::where('id', 10)->first()->id,
                'sub_division_id' => SubDivision::where('id', 53)->first()->id,
                'groupement' => '',
                'lieu_dit' => 'Mambila' ,
                'zone'=>'urbain',
                'numero_folio' => '1' ,
                'volume' => '1' ,
                'superficie_du_TF_mere' => 4000 ,
                'etat_terrain' => 'non_batit',
                'provenance_TF' => 'mutation_totale',
                'numero_bordereau_analytique' => '1',
                'coordonnees' => json_encode($coordinates[0]),
                'limit_nord' => 'route' ,
                'limit_sud' => 'route',
                'limit_est' => 'route',
                'limit_ouest' => 'route',
            ]);
            TitreFoncier::create([
                'uuid' => Str::uuid(),
                'numero_titre_foncier' => Str::random(11),
                'date_de_delivrance_du_TF' => '2022-01-01',
                'numero_du_duplicata' => 1,
                'region_id' => Region::where('id', 2)->first()->id,
                'division_id' => Division::where('id', 11)->first()->id,
                'sub_division_id' => SubDivision::where('id', 60)->first()->id,
                'groupement' => '',
                'lieu_dit' => 'Mambila' ,
                'zone'=>'rurale',
                'numero_folio' => '1' ,
                'volume' => '1' ,
                'superficie_du_TF_mere' => 4000 ,
                'etat_terrain' => 'non_batit',
                'provenance_TF' => 'mutation_totale',
                'numero_bordereau_analytique' => '1',
                'coordonnees' => json_encode($coordinates[0]),
                'limit_nord' => 'route' ,
                'limit_sud' => 'route',
                'limit_est' => 'route',
                'limit_ouest' => 'route',
            ]);
            TitreFoncier::create([
                'uuid' => Str::uuid(),
                'numero_titre_foncier' => Str::random(11),
                'date_de_delivrance_du_TF' => '2022-01-01',
                'numero_du_duplicata' => 1,
                'region_id' => Region::where('id', 2)->first()->id,
                'division_id' => Division::where('id', 11)->first()->id,
                'sub_division_id' => SubDivision::where('id', 60)->first()->id,
                'groupement' => '',
                'lieu_dit' => 'Mambila' ,
                'zone'=>'rurale',
                'numero_folio' => '1' ,
                'volume' => '1' ,
                'superficie_du_TF_mere' => 4000 ,
                'etat_terrain' => 'non_batit',
                'provenance_TF' => 'mutation_totale',
                'numero_bordereau_analytique' => '1',
                'coordonnees' => json_encode($coordinates[0]),
                'limit_nord' => 'route' ,
                'limit_sud' => 'route',
                'limit_est' => 'route',
                'limit_ouest' => 'route',
            ]);TitreFoncier::create([
                'uuid' => Str::uuid(),
                'numero_titre_foncier' => Str::random(11),
                'date_de_delivrance_du_TF' => '2022-01-01',
                'numero_du_duplicata' => 1,
                'region_id' => Region::where('id', 3)->first()->id,
                'division_id' => Division::where('id', 16)->first()->id,
                'sub_division_id' => SubDivision::where('id', 90)->first()->id,
                'groupement' => '',
                'lieu_dit' => 'Mambila' ,
                'zone'=>'rurale',
                'numero_folio' => '1' ,
                'volume' => '1' ,
                'superficie_du_TF_mere' => 4000 ,
                'etat_terrain' => 'non_batit',
                'provenance_TF' => 'mutation_totale',
                'numero_bordereau_analytique' => '1',
                'coordonnees' => json_encode($coordinates[0]),
                'limit_nord' => 'route' ,
                'limit_sud' => 'route',
                'limit_est' => 'route',
                'limit_ouest' => 'route',
            ]);TitreFoncier::create([
                'uuid' => Str::uuid(),
                'numero_titre_foncier' => Str::random(11),
                'date_de_delivrance_du_TF' => '2022-01-01',
                'numero_du_duplicata' => 1,
                'region_id' => Region::where('id', 2)->first()->id,
                'division_id' => Division::where('id', 16)->first()->id,
                'sub_division_id' => SubDivision::where('id', 91)->first()->id,
                'groupement' => '',
                'lieu_dit' => 'Mambila' ,
                'zone'=>'rurale',
                'numero_folio' => '1' ,
                'volume' => '1' ,
                'superficie_du_TF_mere' => 4000 ,
                'etat_terrain' => 'non_batit',
                'provenance_TF' => 'mutation_totale',
                'numero_bordereau_analytique' => '1',
                'coordonnees' => json_encode($coordinates[0]),
                'limit_nord' => 'route' ,
                'limit_sud' => 'route',
                'limit_est' => 'route',
                'limit_ouest' => 'route',
            ]);TitreFoncier::create([
                'uuid' => Str::uuid(),
                'numero_titre_foncier' => Str::random(11),
                'date_de_delivrance_du_TF' => '2022-01-01',
                'numero_du_duplicata' => 1,
                'region_id' => Region::where('id', 2)->first()->id,
                'division_id' => Division::where('id', 17)->first()->id,
                'sub_division_id' => SubDivision::where('id', 95)->first()->id,
                'groupement' => '',
                'lieu_dit' => 'Mambila' ,
                'zone'=>'urbain',
                'numero_folio' => '1' ,
                'volume' => '1' ,
                'superficie_du_TF_mere' => 4000 ,
                'etat_terrain' => 'non_batit',
                'provenance_TF' => 'mutation_totale',
                'numero_bordereau_analytique' => '1',
                'coordonnees' => json_encode($coordinates[0]),
                'limit_nord' => 'route' ,
                'limit_sud' => 'route',
                'limit_est' => 'route',
                'limit_ouest' => 'route',
            ]);TitreFoncier::create([
                'uuid' => Str::uuid(),
                'numero_titre_foncier' => Str::random(11),
                'date_de_delivrance_du_TF' => '2022-01-01',
                'numero_du_duplicata' => 1,
                'region_id' => Region::where('id', 2)->first()->id,
                'division_id' => Division::where('id', 17)->first()->id,
                'sub_division_id' => SubDivision::where('id', 96)->first()->id,
                'groupement' => '',
                'lieu_dit' => 'Mambila' ,
                'zone'=>'urbain',
                'numero_folio' => '1' ,
                'volume' => '1' ,
                'superficie_du_TF_mere' => 4000 ,
                'etat_terrain' => 'non_batit',
                'provenance_TF' => 'mutation_totale',
                'numero_bordereau_analytique' => '1',
                'coordonnees' => json_encode($coordinates[0]),
                'limit_nord' => 'route' ,
                'limit_sud' => 'route',
                'limit_est' => 'route',
                'limit_ouest' => 'route',
            ]);TitreFoncier::create([
                'uuid' => Str::uuid(),
                'numero_titre_foncier' => Str::random(11),
                'date_de_delivrance_du_TF' => '2022-01-01',
                'numero_du_duplicata' => 1,
                'region_id' => Region::where('id', 2)->first()->id,
                'division_id' => Division::where('id', 18)->first()->id,
                'sub_division_id' => SubDivision::where('id', 108)->first()->id,
                'groupement' => '',
                'lieu_dit' => 'Mambila' ,
                'zone'=>'urbain',
                'numero_folio' => '1' ,
                'volume' => '1' ,
                'superficie_du_TF_mere' => 4000 ,
                'etat_terrain' => 'batit',
                'provenance_TF' => 'mutation_totale',
                'numero_bordereau_analytique' => '1',
                'coordonnees' => json_encode($coordinates[0]),
                'limit_nord' => 'route' ,
                'limit_sud' => 'route',
                'limit_est' => 'route',
                'limit_ouest' => 'route',
            ]);TitreFoncier::create([
                'uuid' => Str::uuid(),
                'numero_titre_foncier' => Str::random(11),
                'date_de_delivrance_du_TF' => '2022-01-01',
                'numero_du_duplicata' => 1,
                'region_id' => Region::where('id', 2)->first()->id,
                'division_id' => Division::where('id', 18)->first()->id,
                'sub_division_id' => SubDivision::where('id', 114)->first()->id,
                'groupement' => '',
                'lieu_dit' => 'Mambila' ,
                'zone'=>'urbain',
                'numero_folio' => '1' ,
                'volume' => '1' ,
                'superficie_du_TF_mere' => 4000 ,
                'etat_terrain' => 'batit',
                'provenance_TF' => 'imma_directe',
                'numero_bordereau_analytique' => '1',
                'coordonnees' => json_encode($coordinates[0]),
                'limit_nord' => 'route' ,
                'limit_sud' => 'route',
                'limit_est' => 'route',
                'limit_ouest' => 'route',
            ]);TitreFoncier::create([
                'uuid' => Str::uuid(),
                'numero_titre_foncier' => Str::random(11),
                'date_de_delivrance_du_TF' => '2023-01-01',
                'numero_du_duplicata' => 1,
                'region_id' => Region::where('id', 2)->first()->id,
                'division_id' => Division::where('id', 11)->first()->id,
                'sub_division_id' => SubDivision::where('id', 60)->first()->id,
                'groupement' => '',
                'lieu_dit' => 'Mambila' ,
                'zone'=>'urbain',
                'numero_folio' => '1' ,
                'volume' => '1' ,
                'superficie_du_TF_mere' => 4000 ,
                'etat_terrain' => 'batit',
                'provenance_TF' => 'imma_directe',
                'numero_bordereau_analytique' => '1',
                'coordonnees' => json_encode($coordinates[0]),
                'limit_nord' => 'route' ,
                'limit_sud' => 'route',
                'limit_est' => 'route',
                'limit_ouest' => 'route',
            ]);TitreFoncier::create([
                'uuid' => Str::uuid(),
                'numero_titre_foncier' => Str::random(11),
                'date_de_delivrance_du_TF' => '2023-01-01',
                'numero_du_duplicata' => 1,
                'region_id' => Region::where('id', 2)->first()->id,
                'division_id' => Division::where('id', 11)->first()->id,
                'sub_division_id' => SubDivision::where('id', 60)->first()->id,
                'groupement' => '',
                'lieu_dit' => 'Mambila' ,
                'zone'=>'urbain',
                'numero_folio' => '1' ,
                'volume' => '1' ,
                'superficie_du_TF_mere' => 4000 ,
                'etat_terrain' => 'batit',
                'provenance_TF' => 'imma_directe',
                'numero_bordereau_analytique' => '1',
                'coordonnees' => json_encode($coordinates[0]),
                'limit_nord' => 'route' ,
                'limit_sud' => 'route',
                'limit_est' => 'route',
                'limit_ouest' => 'route',
            ]);TitreFoncier::create([
                'uuid' => Str::uuid(),
                'numero_titre_foncier' => Str::random(11),
                'date_de_delivrance_du_TF' => '2023-01-01',
                'numero_du_duplicata' => 1,
                'region_id' => Region::where('id', 2)->first()->id,
                'division_id' => Division::where('id', 11)->first()->id,
                'sub_division_id' => SubDivision::where('id', 60)->first()->id,
                'groupement' => '',
                'lieu_dit' => 'Mambila' ,
                'zone'=>'urbain',
                'numero_folio' => '1' ,
                'volume' => '1' ,
                'superficie_du_TF_mere' => 4000 ,
                'etat_terrain' => 'batit',
                'provenance_TF' => 'imma_directe',
                'numero_bordereau_analytique' => '1',
                'coordonnees' => json_encode($coordinates[0]),
                'limit_nord' => 'route' ,
                'limit_sud' => 'route',
                'limit_est' => 'route',
                'limit_ouest' => 'route',
            ]);

            TitreFoncier::create([
                'uuid' => Str::uuid(),
                'numero_titre_foncier' => Str::random(11),
                'date_de_delivrance_du_TF' => '1990-04-18',
                'numero_du_duplicata' => 54,
                'region_id' => Region::where('id', 1)->first()->id,
                'division_id' => Division::where('id', 26)->first()->id,
                'sub_division_id' => SubDivision::where('id', 171)->first()->id,
                'groupement' => '',
                'lieu_dit' => 'Leonard Greene' ,
                'zone'=>'rurale',
                'numero_folio' => '49' ,
                'volume' => '95' ,
                'superficie_du_TF_mere' => 5000 ,
                'etat_terrain' => 'batit',
                'provenance_TF' => 'imma_directe',
                'numero_bordereau_analytique' => '2',
                'coordonnees' => json_encode($coordinates[0]),
                'limit_nord' => 'route' ,
                'limit_sud' => 'route',
                'limit_est' => 'route',
                'limit_ouest' => 'route',
            ]);
            TitreFoncier::create([
                'uuid' => Str::uuid(),
                'numero_titre_foncier' => Str::random(11),
                'date_de_delivrance_du_TF' => '1999-08-12',
                'numero_du_duplicata' => 1,
                'region_id' => Region::where('id', 2)->first()->id,
                'division_id' => Division::where('id', 18)->first()->id,
                'sub_division_id' => SubDivision::where('id', 114)->first()->id,
                'groupement' => '',
                'lieu_dit' => 'Mambila' ,
                'zone'=>'rurale',
                'numero_folio' => '21' ,
                'volume' => '1' ,
                'superficie_du_TF_mere' => 1000 ,
                'etat_terrain' => 'batit',
                'provenance_TF' => 'imma_directe',
                'numero_bordereau_analytique' => '1',
                'coordonnees' => json_encode($coordinates[0]),
                'limit_nord' => 'route' ,
                'limit_sud' => 'route',
                'limit_est' => 'route',
                'limit_ouest' => 'route',
            ]);

            TitreFoncier::create([
                'uuid' => Str::uuid(),
                'numero_titre_foncier' => Str::random(11),
                'date_de_delivrance_du_TF' => '1997-07-14',
                'numero_du_duplicata' => 1,
                'region_id' => Region::where('id', 3)->first()->id,
                'division_id' => Division::where('id', 12)->first()->id,
                'sub_division_id' => SubDivision::where('id', 214)->first()->id,
                'groupement' => '',
                'lieu_dit' => 'Mambila' ,
                'zone'=>'urbain',
                'numero_folio' => '15' ,
                'volume' => '5' ,
                'superficie_du_TF_mere' => 5000 ,
                'etat_terrain' => 'batit',
                'provenance_TF' => 'imma_directe',
                'numero_bordereau_analytique' => '1',
                'coordonnees' => json_encode($coordinates[0]),
                'limit_nord' => 'route' ,
                'limit_sud' => 'route',
                'limit_est' => 'route',
                'limit_ouest' => 'route',
            ]);

            TitreFoncier::create([
                'uuid' => Str::uuid(),
                'numero_titre_foncier' => Str::random(11),
                'date_de_delivrance_du_TF' => '1995-03-02',
                'numero_du_duplicata' => 1,
                'region_id' => Region::where('id', 1)->first()->id,
                'division_id' => Division::where('id', 14)->first()->id,
                'sub_division_id' => SubDivision::where('id', 214)->first()->id,
                'groupement' => '',
                'lieu_dit' => 'Mambila' ,
                'zone'=>'rurale',
                'numero_folio' => '26' ,
                'volume' => '6' ,
                'superficie_du_TF_mere' => 7000 ,
                'etat_terrain' => 'batit',
                'provenance_TF' => 'imma_directe',
                'numero_bordereau_analytique' => '5',
                'coordonnees' => json_encode($coordinates[0]),
                'limit_nord' => 'route' ,
                'limit_sud' => 'route',
                'limit_est' => 'route',
                'limit_ouest' => 'route',
            ]);


            for ($i = 0; $i < 50; $i++) {

                $TitreFon = TitreFoncier::create([
                    'uuid' => Str::uuid(),
                    'numero_titre_foncier' => Str::random(11),
                    'date_de_delivrance_du_TF' => '1999-08-12',
                    'numero_du_duplicata' => 1,
                    'region_id' => Region::where('id', 2)->first()->id,
                    'division_id' => Division::where('id', 18)->first()->id,
                    'sub_division_id' => SubDivision::where('id', 114)->first()->id,
                    'groupement' => '',
                    'lieu_dit' => 'Mambila' ,
                    'zone'=>'rurale',
                    'numero_folio' => '21' ,
                    'volume' => '1' ,
                    'superficie_du_TF_mere' => 1000 ,
                    'etat_terrain' => 'batit',
                    'provenance_TF' => 'imma_directe',
                    'numero_bordereau_analytique' => '1',
                    'coordonnees' => json_encode($coordinates[0]),
                    'limit_nord' => 'route' ,
                    'limit_sud' => 'route',
                    'limit_est' => 'route',
                    'limit_ouest' => 'route',
                ]);
            }

            for ($i = 0; $i < 50; $i++) {

                $TitreFon = TitreFoncier::create([
                    'uuid' => Str::uuid(),
                    'numero_titre_foncier' => Str::random(11),
                    'date_de_delivrance_du_TF' => '1999-08-12',
                    'numero_du_duplicata' => 1,
                    'region_id' => Region::where('id', 2)->first()->id,
                    'division_id' => Division::where('id', 18)->first()->id,
                    'sub_division_id' => SubDivision::where('id', 114)->first()->id,
                    'groupement' => '',
                    'lieu_dit' => 'Mambila' ,
                    'zone'=>'rurale',
                    'numero_folio' => '21' ,
                    'volume' => '1' ,
                    'superficie_du_TF_mere' => 1000 ,
                    'etat_terrain' => 'batit',
                    'provenance_TF' => 'imma_directe',
                    'numero_bordereau_analytique' => '1',
                    'coordonnees' => json_encode($coordinates[0]),
                    'limit_nord' => 'route' ,
                    'limit_sud' => 'route',
                    'limit_est' => 'route',
                    'limit_ouest' => 'route',
                ]);
            }

            for ($i = 0; $i < 50; $i++) {

                $TitreFon = TitreFoncier::create([
                    'uuid' => Str::uuid(),
                    'numero_titre_foncier' => Str::random(11),
                    'date_de_delivrance_du_TF' => '1999-08-12',
                    'numero_du_duplicata' => 1,
                    'region_id' => Region::where('id', 2)->first()->id,
                    'division_id' => Division::where('id', 18)->first()->id,
                    'sub_division_id' => SubDivision::where('id', 114)->first()->id,
                    'groupement' => '',
                    'lieu_dit' => 'Mambila' ,
                    'zone'=>'rurale',
                    'numero_folio' => '21' ,
                    'volume' => '1' ,
                    'superficie_du_TF_mere' => 1000 ,
                    'etat_terrain' => 'batit',
                    'provenance_TF' => 'imma_directe',
                    'numero_bordereau_analytique' => '1',
                    'coordonnees' => json_encode($coordinates[0]),
                    'limit_nord' => 'route' ,
                    'limit_sud' => 'route',
                    'limit_est' => 'route',
                    'limit_ouest' => 'route',
                ]);
            }

            for ($i = 0; $i < 50; $i++) {

                $TitreFon = TitreFoncier::create([
                    'uuid' => Str::uuid(),
                    'numero_titre_foncier' => Str::random(11),
                    'date_de_delivrance_du_TF' => '1999-08-12',
                    'numero_du_duplicata' => 1,
                    'region_id' => Region::where('id', 2)->first()->id,
                    'division_id' => Division::where('id', 18)->first()->id,
                    'sub_division_id' => SubDivision::where('id', 114)->first()->id,
                    'groupement' => '',
                    'lieu_dit' => 'Mambila' ,
                    'zone'=>'rurale',
                    'numero_folio' => '21' ,
                    'volume' => '1' ,
                    'superficie_du_TF_mere' => 1000 ,
                    'etat_terrain' => 'batit',
                    'provenance_TF' => 'imma_directe',
                    'numero_bordereau_analytique' => '1',
                    'coordonnees' => json_encode($coordinates[0]),
                    'limit_nord' => 'route' ,
                    'limit_sud' => 'route',
                    'limit_est' => 'route',
                    'limit_ouest' => 'route',
                ]);
            }

            for ($i = 0; $i < 50; $i++) {

            $TitreFon = TitreFoncier::create([
                'uuid' => Str::uuid(),
                'numero_titre_foncier' => Str::random(11),
                'date_de_delivrance_du_TF' => '1999-08-12',
                'numero_du_duplicata' => 1,
                'region_id' => Region::where('id', 2)->first()->id,
                'division_id' => Division::where('id', 18)->first()->id,
                'sub_division_id' => SubDivision::where('id', 114)->first()->id,
                'groupement' => '',
                'lieu_dit' => 'Mambila' ,
                'zone'=>'rurale',
                'numero_folio' => '21' ,
                'volume' => '1' ,
                'superficie_du_TF_mere' => 1000 ,
                'etat_terrain' => 'batit',
                'provenance_TF' => 'imma_directe',
                'numero_bordereau_analytique' => '1',
                'coordonnees' => json_encode($coordinates[0]),
                'limit_nord' => 'route' ,
                'limit_sud' => 'route',
                'limit_est' => 'route',
                'limit_ouest' => 'route',
            ]);
        }

            TitreFoncier::create([
                'uuid' => Str::uuid(),
                'numero_titre_foncier' => Str::random(11),
                'date_de_delivrance_du_TF' => '1994-10-02',
                'numero_du_duplicata' => 2,
                'region_id' => Region::where('id', 3)->first()->id,
                'division_id' => Division::where('id', 18)->first()->id,
                'sub_division_id' => SubDivision::where('id', 114)->first()->id,
                'groupement' => '',
                'lieu_dit' => 'Mambila' ,
                'zone'=>'rurale',
                'numero_folio' => '21' ,
                'volume' => '1' ,
                'superficie_du_TF_mere' => 1000 ,
                'etat_terrain' => 'batit',
                'provenance_TF' => 'imma_directe',
                'numero_bordereau_analytique' => '1',
                'coordonnees' => json_encode($coordinates[0]),
                'limit_nord' => 'route' ,
                'limit_sud' => 'route',
                'limit_est' => 'route',
                'limit_ouest' => 'route',
            ]);

            TitreFoncier::create([
                'uuid' => Str::uuid(),
                'numero_titre_foncier' => Str::random(11),
                'date_de_delivrance_du_TF' => '1999-08-12',
                'numero_du_duplicata' => 1,
                'region_id' => Region::where('id', 2)->first()->id,
                'division_id' => Division::where('id', 18)->first()->id,
                'sub_division_id' => SubDivision::where('id', 114)->first()->id,
                'groupement' => '',
                'lieu_dit' => 'Mambila' ,
                'zone'=>'rurale',
                'numero_folio' => '21' ,
                'volume' => '1' ,
                'superficie_du_TF_mere' => 1000 ,
                'etat_terrain' => 'batit',
                'provenance_TF' => 'imma_directe',
                'numero_bordereau_analytique' => '1',
                'coordonnees' => json_encode($coordinates[0]),
                'limit_nord' => 'route' ,
                'limit_sud' => 'route',
                'limit_est' => 'route',
                'limit_ouest' => 'route',
            ]);

            TitreFoncier::create([
                'uuid' => Str::uuid(),
                'numero_titre_foncier' => Str::random(11),
                'date_de_delivrance_du_TF' => '1999-08-12',
                'numero_du_duplicata' => 1,
                'region_id' => Region::where('id', 2)->first()->id,
                'division_id' => Division::where('id', 18)->first()->id,
                'sub_division_id' => SubDivision::where('id', 114)->first()->id,
                'groupement' => '',
                'lieu_dit' => 'Mambila' ,
                'zone'=>'rurale',
                'numero_folio' => '21' ,
                'volume' => '1' ,
                'superficie_du_TF_mere' => 1000 ,
                'etat_terrain' => 'batit',
                'provenance_TF' => 'imma_directe',
                'numero_bordereau_analytique' => '1',
                'coordonnees' => json_encode($coordinates[0]),
                'limit_nord' => 'route' ,
                'limit_sud' => 'route',
                'limit_est' => 'route',
                'limit_ouest' => 'route',
            ]);


            TitreFoncier::create([
                'uuid' => Str::uuid(),
                'numero_titre_foncier' => Str::random(11),
                'date_de_delivrance_du_TF' => '1999-08-12',
                'numero_du_duplicata' => 1,
                'region_id' => Region::where('id', 2)->first()->id,
                'division_id' => Division::where('id', 18)->first()->id,
                'sub_division_id' => SubDivision::where('id', 114)->first()->id,
                'groupement' => '',
                'lieu_dit' => 'Mambila' ,
                'zone'=>'rurale',
                'numero_folio' => '21' ,
                'volume' => '1' ,
                'superficie_du_TF_mere' => 1000 ,
                'etat_terrain' => 'batit',
                'provenance_TF' => 'imma_directe',
                'numero_bordereau_analytique' => '1',
                'coordonnees' => json_encode($coordinates[0]),
                'limit_nord' => 'route' ,
                'limit_sud' => 'route',
                'limit_est' => 'route',
                'limit_ouest' => 'route',
            ]);


            TitreFoncier::create([
                'uuid' => Str::uuid(),
                'numero_titre_foncier' => Str::random(11),
                'date_de_delivrance_du_TF' => '1999-08-12',
                'numero_du_duplicata' => 1,
                'region_id' => Region::where('id', 2)->first()->id,
                'division_id' => Division::where('id', 18)->first()->id,
                'sub_division_id' => SubDivision::where('id', 114)->first()->id,
                'groupement' => '',
                'lieu_dit' => 'Mambila' ,
                'zone'=>'rurale',
                'numero_folio' => '21' ,
                'volume' => '1' ,
                'superficie_du_TF_mere' => 1000 ,
                'etat_terrain' => 'batit',
                'provenance_TF' => 'imma_directe',
                'numero_bordereau_analytique' => '1',
                'coordonnees' => json_encode($coordinates[0]),
                'limit_nord' => 'route' ,
                'limit_sud' => 'route',
                'limit_est' => 'route',
                'limit_ouest' => 'route',
            ]);


            TitreFoncier::create([
                'uuid' => Str::uuid(),
                'numero_titre_foncier' => Str::random(11),
                'date_de_delivrance_du_TF' => '1999-08-12',
                'numero_du_duplicata' => 1,
                'region_id' => Region::where('id', 2)->first()->id,
                'division_id' => Division::where('id', 18)->first()->id,
                'sub_division_id' => SubDivision::where('id', 114)->first()->id,
                'groupement' => '',
                'lieu_dit' => 'Mambila' ,
                'zone'=>'rurale',
                'numero_folio' => '21' ,
                'volume' => '1' ,
                'superficie_du_TF_mere' => 1000 ,
                'etat_terrain' => 'batit',
                'provenance_TF' => 'imma_directe',
                'numero_bordereau_analytique' => '1',
                'coordonnees' => json_encode($coordinates[0]),
                'limit_nord' => 'route' ,
                'limit_sud' => 'route',
                'limit_est' => 'route',
                'limit_ouest' => 'route',
            ]);


            TitreFoncier::create([
                'uuid' => Str::uuid(),
                'numero_titre_foncier' => Str::random(11),
                'date_de_delivrance_du_TF' => '1999-08-12',
                'numero_du_duplicata' => 1,
                'region_id' => Region::where('id', 2)->first()->id,
                'division_id' => Division::where('id', 18)->first()->id,
                'sub_division_id' => SubDivision::where('id', 114)->first()->id,
                'groupement' => '',
                'lieu_dit' => 'Mambila' ,
                'zone'=>'rurale',
                'numero_folio' => '21' ,
                'volume' => '1' ,
                'superficie_du_TF_mere' => 1000 ,
                'etat_terrain' => 'batit',
                'provenance_TF' => 'imma_directe',
                'numero_bordereau_analytique' => '1',
                'coordonnees' => json_encode($coordinates[0]),
                'limit_nord' => 'route' ,
                'limit_sud' => 'route',
                'limit_est' => 'route',
                'limit_ouest' => 'route',
            ]);


            TitreFoncier::create([
                'uuid' => Str::uuid(),
                'numero_titre_foncier' => Str::random(11),
                'date_de_delivrance_du_TF' => '1999-08-12',
                'numero_du_duplicata' => 1,
                'region_id' => Region::where('id', 2)->first()->id,
                'division_id' => Division::where('id', 18)->first()->id,
                'sub_division_id' => SubDivision::where('id', 114)->first()->id,
                'groupement' => '',
                'lieu_dit' => 'Mambila' ,
                'zone'=>'rurale',
                'numero_folio' => '21' ,
                'volume' => '1' ,
                'superficie_du_TF_mere' => 1000 ,
                'etat_terrain' => 'batit',
                'provenance_TF' => 'imma_directe',
                'numero_bordereau_analytique' => '1',
                'coordonnees' => json_encode($coordinates[0]),
                'limit_nord' => 'route' ,
                'limit_sud' => 'route',
                'limit_est' => 'route',
                'limit_ouest' => 'route',
            ]);


            TitreFoncier::create([
                'uuid' => Str::uuid(),
                'numero_titre_foncier' => Str::random(11),
                'date_de_delivrance_du_TF' => '1999-08-12',
                'numero_du_duplicata' => 1,
                'region_id' => Region::where('id', 2)->first()->id,
                'division_id' => Division::where('id', 18)->first()->id,
                'sub_division_id' => SubDivision::where('id', 114)->first()->id,
                'groupement' => '',
                'lieu_dit' => 'Mambila' ,
                'zone'=>'rurale',
                'numero_folio' => '21' ,
                'volume' => '1' ,
                'superficie_du_TF_mere' => 1000 ,
                'etat_terrain' => 'batit',
                'provenance_TF' => 'imma_directe',
                'numero_bordereau_analytique' => '1',
                'coordonnees' => json_encode($coordinates[0]),
                'limit_nord' => 'route' ,
                'limit_sud' => 'route',
                'limit_est' => 'route',
                'limit_ouest' => 'route',
            ]);


            TitreFoncier::create([
                'uuid' => Str::uuid(),
                'numero_titre_foncier' => Str::random(11),
                'date_de_delivrance_du_TF' => '1999-08-12',
                'numero_du_duplicata' => 1,
                'region_id' => Region::where('id', 2)->first()->id,
                'division_id' => Division::where('id', 18)->first()->id,
                'sub_division_id' => SubDivision::where('id', 114)->first()->id,
                'groupement' => '',
                'lieu_dit' => 'Mambila' ,
                'zone'=>'rurale',
                'numero_folio' => '21' ,
                'volume' => '1' ,
                'superficie_du_TF_mere' => 1000 ,
                'etat_terrain' => 'batit',
                'provenance_TF' => 'imma_directe',
                'numero_bordereau_analytique' => '1',
                'coordonnees' => json_encode($coordinates[0]),
                'limit_nord' => 'route' ,
                'limit_sud' => 'route',
                'limit_est' => 'route',
                'limit_ouest' => 'route',
            ]);


            TitreFoncier::create([
                'uuid' => Str::uuid(),
                'numero_titre_foncier' => Str::random(11),
                'date_de_delivrance_du_TF' => '1999-08-12',
                'numero_du_duplicata' => 1,
                'region_id' => Region::where('id', 2)->first()->id,
                'division_id' => Division::where('id', 18)->first()->id,
                'sub_division_id' => SubDivision::where('id', 114)->first()->id,
                'groupement' => '',
                'lieu_dit' => 'Mambila' ,
                'zone'=>'rurale',
                'numero_folio' => '21' ,
                'volume' => '1' ,
                'superficie_du_TF_mere' => 1000 ,
                'etat_terrain' => 'batit',
                'provenance_TF' => 'imma_directe',
                'numero_bordereau_analytique' => '1',
                'coordonnees' => json_encode($coordinates[0]),
                'limit_nord' => 'route' ,
                'limit_sud' => 'route',
                'limit_est' => 'route',
                'limit_ouest' => 'route',
            ]);


            TitreFoncier::create([
                'uuid' => Str::uuid(),
                'numero_titre_foncier' => Str::random(11),
                'date_de_delivrance_du_TF' => '1999-08-12',
                'numero_du_duplicata' => 1,
                'region_id' => Region::where('id', 2)->first()->id,
                'division_id' => Division::where('id', 18)->first()->id,
                'sub_division_id' => SubDivision::where('id', 114)->first()->id,
                'groupement' => '',
                'lieu_dit' => 'Mambila' ,
                'zone'=>'rurale',
                'numero_folio' => '21' ,
                'volume' => '1' ,
                'superficie_du_TF_mere' => 1000 ,
                'etat_terrain' => 'batit',
                'provenance_TF' => 'imma_directe',
                'numero_bordereau_analytique' => '1',
                'coordonnees' => json_encode($coordinates[0]),
                'limit_nord' => 'route' ,
                'limit_sud' => 'route',
                'limit_est' => 'route',
                'limit_ouest' => 'route',
            ]);


            TitreFoncier::create([
                'uuid' => Str::uuid(),
                'numero_titre_foncier' => Str::random(11),
                'date_de_delivrance_du_TF' => '1999-08-12',
                'numero_du_duplicata' => 1,
                'region_id' => Region::where('id', 2)->first()->id,
                'division_id' => Division::where('id', 18)->first()->id,
                'sub_division_id' => SubDivision::where('id', 114)->first()->id,
                'groupement' => '',
                'lieu_dit' => 'Mambila' ,
                'zone'=>'rurale',
                'numero_folio' => '21' ,
                'volume' => '1' ,
                'superficie_du_TF_mere' => 1000 ,
                'etat_terrain' => 'batit',
                'provenance_TF' => 'imma_directe',
                'numero_bordereau_analytique' => '1',
                'coordonnees' => json_encode($coordinates[0]),
                'limit_nord' => 'route' ,
                'limit_sud' => 'route',
                'limit_est' => 'route',
                'limit_ouest' => 'route',
            ]);


            TitreFoncier::create([
                'uuid' => Str::uuid(),
                'numero_titre_foncier' => Str::random(11),
                'date_de_delivrance_du_TF' => '1999-08-12',
                'numero_du_duplicata' => 1,
                'region_id' => Region::where('id', 2)->first()->id,
                'division_id' => Division::where('id', 18)->first()->id,
                'sub_division_id' => SubDivision::where('id', 114)->first()->id,
                'groupement' => '',
                'lieu_dit' => 'Mambila' ,
                'zone'=>'rurale',
                'numero_folio' => '21' ,
                'volume' => '1' ,
                'superficie_du_TF_mere' => 1000 ,
                'etat_terrain' => 'batit',
                'provenance_TF' => 'imma_directe',
                'numero_bordereau_analytique' => '1',
                'coordonnees' => json_encode($coordinates[0]),
                'limit_nord' => 'route' ,
                'limit_sud' => 'route',
                'limit_est' => 'route',
                'limit_ouest' => 'route',
            ]);


            TitreFoncier::create([
                'uuid' => Str::uuid(),
                'numero_titre_foncier' => Str::random(11),
                'date_de_delivrance_du_TF' => '1999-08-12',
                'numero_du_duplicata' => 1,
                'region_id' => Region::where('id', 2)->first()->id,
                'division_id' => Division::where('id', 18)->first()->id,
                'sub_division_id' => SubDivision::where('id', 114)->first()->id,
                'groupement' => '',
                'lieu_dit' => 'Mambila' ,
                'zone'=>'rurale',
                'numero_folio' => '21' ,
                'volume' => '1' ,
                'superficie_du_TF_mere' => 1000 ,
                'etat_terrain' => 'batit',
                'provenance_TF' => 'imma_directe',
                'numero_bordereau_analytique' => '1',
                'coordonnees' => json_encode($coordinates[0]),
                'limit_nord' => 'route' ,
                'limit_sud' => 'route',
                'limit_est' => 'route',
                'limit_ouest' => 'route',
            ]);



            TitreFoncier::create([
                'uuid' => Str::uuid(),
                'numero_titre_foncier' => Str::random(11),
                'date_de_delivrance_du_TF' => '1999-08-12',
                'numero_du_duplicata' => 1,
                'region_id' => Region::where('id', 2)->first()->id,
                'division_id' => Division::where('id', 18)->first()->id,
                'sub_division_id' => SubDivision::where('id', 114)->first()->id,
                'groupement' => '',
                'lieu_dit' => 'Mambila' ,
                'zone'=>'rurale',
                'numero_folio' => '21' ,
                'volume' => '1' ,
                'superficie_du_TF_mere' => 1000 ,
                'etat_terrain' => 'batit',
                'provenance_TF' => 'imma_directe',
                'numero_bordereau_analytique' => '1',
                'coordonnees' => json_encode($coordinates[0]),
                'limit_nord' => 'route' ,
                'limit_sud' => 'route',
                'limit_est' => 'route',
                'limit_ouest' => 'route',
            ]);


            TitreFoncier::create([
                'uuid' => Str::uuid(),
                'numero_titre_foncier' => Str::random(11),
                'date_de_delivrance_du_TF' => '1999-08-12',
                'numero_du_duplicata' => 1,
                'region_id' => Region::where('id', 2)->first()->id,
                'division_id' => Division::where('id', 18)->first()->id,
                'sub_division_id' => SubDivision::where('id', 114)->first()->id,
                'groupement' => '',
                'lieu_dit' => 'Mambila' ,
                'zone'=>'rurale',
                'numero_folio' => '21' ,
                'volume' => '1' ,
                'superficie_du_TF_mere' => 1000 ,
                'etat_terrain' => 'batit',
                'provenance_TF' => 'imma_directe',
                'numero_bordereau_analytique' => '1',
                'coordonnees' => json_encode($coordinates[0]),
                'limit_nord' => 'route' ,
                'limit_sud' => 'route',
                'limit_est' => 'route',
                'limit_ouest' => 'route',
            ]);


            TitreFoncier::create([
                'uuid' => Str::uuid(),
                'numero_titre_foncier' => Str::random(11),
                'date_de_delivrance_du_TF' => '1999-08-12',
                'numero_du_duplicata' => 1,
                'region_id' => Region::where('id', 2)->first()->id,
                'division_id' => Division::where('id', 18)->first()->id,
                'sub_division_id' => SubDivision::where('id', 114)->first()->id,
                'groupement' => '',
                'lieu_dit' => 'Mambila' ,
                'zone'=>'rurale',
                'numero_folio' => '21' ,
                'volume' => '1' ,
                'superficie_du_TF_mere' => 1000 ,
                'etat_terrain' => 'batit',
                'provenance_TF' => 'imma_directe',
                'numero_bordereau_analytique' => '1',
                'coordonnees' => json_encode($coordinates[0]),
                'limit_nord' => 'route' ,
                'limit_sud' => 'route',
                'limit_est' => 'route',
                'limit_ouest' => 'route',
            ]);


            TitreFoncier::create([
                'uuid' => Str::uuid(),
                'numero_titre_foncier' => Str::random(11),
                'date_de_delivrance_du_TF' => '1999-08-12',
                'numero_du_duplicata' => 1,
                'region_id' => Region::where('id', 2)->first()->id,
                'division_id' => Division::where('id', 18)->first()->id,
                'sub_division_id' => SubDivision::where('id', 114)->first()->id,
                'groupement' => '',
                'lieu_dit' => 'Mambila' ,
                'zone'=>'rurale',
                'numero_folio' => '21' ,
                'volume' => '1' ,
                'superficie_du_TF_mere' => 1000 ,
                'etat_terrain' => 'batit',
                'provenance_TF' => 'imma_directe',
                'numero_bordereau_analytique' => '1',
                'coordonnees' => json_encode($coordinates[0]),
                'limit_nord' => 'route' ,
                'limit_sud' => 'route',
                'limit_est' => 'route',
                'limit_ouest' => 'route',
            ]);


            TitreFoncier::create([
                'uuid' => Str::uuid(),
                'numero_titre_foncier' => Str::random(11),
                'date_de_delivrance_du_TF' => '1999-08-12',
                'numero_du_duplicata' => 1,
                'region_id' => Region::where('id', 2)->first()->id,
                'division_id' => Division::where('id', 18)->first()->id,
                'sub_division_id' => SubDivision::where('id', 114)->first()->id,
                'groupement' => '',
                'lieu_dit' => 'Mambila' ,
                'zone'=>'rurale',
                'numero_folio' => '21' ,
                'volume' => '1' ,
                'superficie_du_TF_mere' => 1000 ,
                'etat_terrain' => 'batit',
                'provenance_TF' => 'imma_directe',
                'numero_bordereau_analytique' => '1',
                'coordonnees' => json_encode($coordinates[0]),
                'limit_nord' => 'route' ,
                'limit_sud' => 'route',
                'limit_est' => 'route',
                'limit_ouest' => 'route',
            ]);


            TitreFoncier::create([
                'uuid' => Str::uuid(),
                'numero_titre_foncier' => Str::random(11),
                'date_de_delivrance_du_TF' => '1999-08-12',
                'numero_du_duplicata' => 1,
                'region_id' => Region::where('id', 2)->first()->id,
                'division_id' => Division::where('id', 18)->first()->id,
                'sub_division_id' => SubDivision::where('id', 114)->first()->id,
                'groupement' => '',
                'lieu_dit' => 'Mambila' ,
                'zone'=>'rurale',
                'numero_folio' => '21' ,
                'volume' => '1' ,
                'superficie_du_TF_mere' => 1000 ,
                'etat_terrain' => 'batit',
                'provenance_TF' => 'imma_directe',
                'numero_bordereau_analytique' => '1',
                'coordonnees' => json_encode($coordinates[0]),
                'limit_nord' => 'route' ,
                'limit_sud' => 'route',
                'limit_est' => 'route',
                'limit_ouest' => 'route',
            ]);


            TitreFoncier::create([
                'uuid' => Str::uuid(),
                'numero_titre_foncier' => Str::random(11),
                'date_de_delivrance_du_TF' => '1999-08-12',
                'numero_du_duplicata' => 1,
                'region_id' => Region::where('id', 2)->first()->id,
                'division_id' => Division::where('id', 18)->first()->id,
                'sub_division_id' => SubDivision::where('id', 114)->first()->id,
                'groupement' => '',
                'lieu_dit' => 'Mambila' ,
                'zone'=>'rurale',
                'numero_folio' => '21' ,
                'volume' => '1' ,
                'superficie_du_TF_mere' => 1000 ,
                'etat_terrain' => 'batit',
                'provenance_TF' => 'imma_directe',
                'numero_bordereau_analytique' => '1',
                'coordonnees' => json_encode($coordinates[0]),
                'limit_nord' => 'route' ,
                'limit_sud' => 'route',
                'limit_est' => 'route',
                'limit_ouest' => 'route',
            ]);


            TitreFoncier::create([
                'uuid' => Str::uuid(),
                'numero_titre_foncier' => Str::random(11),
                'date_de_delivrance_du_TF' => '1999-08-12',
                'numero_du_duplicata' => 1,
                'region_id' => Region::where('id', 2)->first()->id,
                'division_id' => Division::where('id', 18)->first()->id,
                'sub_division_id' => SubDivision::where('id', 114)->first()->id,
                'groupement' => '',
                'lieu_dit' => 'Mambila' ,
                'zone'=>'rurale',
                'numero_folio' => '21' ,
                'volume' => '1' ,
                'superficie_du_TF_mere' => 1000 ,
                'etat_terrain' => 'batit',
                'provenance_TF' => 'imma_directe',
                'numero_bordereau_analytique' => '1',
                'coordonnees' => json_encode($coordinates[0]),
                'limit_nord' => 'route' ,
                'limit_sud' => 'route',
                'limit_est' => 'route',
                'limit_ouest' => 'route',
            ]);


            TitreFoncier::create([
                'uuid' => Str::uuid(),
                'numero_titre_foncier' => Str::random(11),
                'date_de_delivrance_du_TF' => '1999-08-12',
                'numero_du_duplicata' => 1,
                'region_id' => Region::where('id', 2)->first()->id,
                'division_id' => Division::where('id', 18)->first()->id,
                'sub_division_id' => SubDivision::where('id', 114)->first()->id,
                'groupement' => '',
                'lieu_dit' => 'Mambila' ,
                'zone'=>'rurale',
                'numero_folio' => '21' ,
                'volume' => '1' ,
                'superficie_du_TF_mere' => 1000 ,
                'etat_terrain' => 'batit',
                'provenance_TF' => 'imma_directe',
                'numero_bordereau_analytique' => '1',
                'coordonnees' => json_encode($coordinates[0]),
                'limit_nord' => 'route' ,
                'limit_sud' => 'route',
                'limit_est' => 'route',
                'limit_ouest' => 'route',
            ]);


            TitreFoncier::create([
                'uuid' => Str::uuid(),
                'numero_titre_foncier' => Str::random(11),
                'date_de_delivrance_du_TF' => '1999-08-12',
                'numero_du_duplicata' => 1,
                'region_id' => Region::where('id', 2)->first()->id,
                'division_id' => Division::where('id', 18)->first()->id,
                'sub_division_id' => SubDivision::where('id', 114)->first()->id,
                'groupement' => '',
                'lieu_dit' => 'Mambila' ,
                'zone'=>'rurale',
                'numero_folio' => '21' ,
                'volume' => '1' ,
                'superficie_du_TF_mere' => 1000 ,
                'etat_terrain' => 'batit',
                'provenance_TF' => 'imma_directe',
                'numero_bordereau_analytique' => '1',
                'coordonnees' => json_encode($coordinates[0]),
                'limit_nord' => 'route' ,
                'limit_sud' => 'route',
                'limit_est' => 'route',
                'limit_ouest' => 'route',
            ]);


            TitreFoncier::create([
                'uuid' => Str::uuid(),
                'numero_titre_foncier' => Str::random(11),
                'date_de_delivrance_du_TF' => '1999-08-12',
                'numero_du_duplicata' => 1,
                'region_id' => Region::where('id', 2)->first()->id,
                'division_id' => Division::where('id', 18)->first()->id,
                'sub_division_id' => SubDivision::where('id', 114)->first()->id,
                'groupement' => '',
                'lieu_dit' => 'Mambila' ,
                'zone'=>'rurale',
                'numero_folio' => '21' ,
                'volume' => '1' ,
                'superficie_du_TF_mere' => 1000 ,
                'etat_terrain' => 'batit',
                'provenance_TF' => 'imma_directe',
                'numero_bordereau_analytique' => '1',
                'coordonnees' => json_encode($coordinates[0]),
                'limit_nord' => 'route' ,
                'limit_sud' => 'route',
                'limit_est' => 'route',
                'limit_ouest' => 'route',
            ]);


            TitreFoncier::create([
                'uuid' => Str::uuid(),
                'numero_titre_foncier' => Str::random(11),
                'date_de_delivrance_du_TF' => '1999-08-12',
                'numero_du_duplicata' => 1,
                'region_id' => Region::where('id', 2)->first()->id,
                'division_id' => Division::where('id', 18)->first()->id,
                'sub_division_id' => SubDivision::where('id', 114)->first()->id,
                'groupement' => '',
                'lieu_dit' => 'Mambila' ,
                'zone'=>'rurale',
                'numero_folio' => '21' ,
                'volume' => '1' ,
                'superficie_du_TF_mere' => 1000 ,
                'etat_terrain' => 'batit',
                'provenance_TF' => 'imma_directe',
                'numero_bordereau_analytique' => '1',
                'coordonnees' => json_encode($coordinates[0]),
                'limit_nord' => 'route' ,
                'limit_sud' => 'route',
                'limit_est' => 'route',
                'limit_ouest' => 'route',
            ]);


    }
}
